### ISSUE TITLE
Memefolio/sold panel continuously polls for state 

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#101]
When looking at logs - something (probably a time based subscription) causes the component to continuously call its render method. This is probaly not neccessary (memory leak).
![sold_polls](https://user-images.githubusercontent.com/468572/53174009-13f53580-35e9-11e9-8203-efac064a0430.jpg)

**Comment by madvas** [comment]
This is solved?

**Comment by fbielejec** [comment]
Not to my knowledge. Not a priority though, can be marked as backlog issue.

**Comment by fbielejec** [comment]
There is a now sub used to calculate `bought-on`. Not a bug.
