### ISSUE TITLE
Clicking on items in tx log doesn't work again

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#104]
This was already working https://github.com/district0x/memefactory/issues/78#issuecomment-459628850, as implemented by Juan, now it doesn't work again. Tx log just gets closed when clicking on an item.

**Comment by fbielejec** [comment]
This component produces broken html -> a (etherscan urls) nested inside a (with an inside page href) . It needs a bigger rewrite is this new feature has to work reliably.

**Comment by madvas** [comment]
This is still not working for me. Clicking doesn't close tx log anymore, but it doesn't take to any page.

**Comment by fbielejec** [comment]
Could you please enumerate the transactions for which it's failing?
