### ISSUE TITLE
Meme auction price calculation is wrong

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#106]
I set the starting price to 100ETH, yet the price is decaying starting at 200ETH.

![price_wrong](https://user-images.githubusercontent.com/468572/53332374-7d2fbe00-38f3-11e9-8b1d-aadcb35cbf1f.jpg)

**Comment by jpmonettas** [comment]
@fbielejec I'm not being able to reproduce this
![latest-screenshot](https://user-images.githubusercontent.com/786299/53340889-e2ca7d00-38e8-11e9-81f2-b7e7de49e229.png)

**Comment by fbielejec** [comment]
Caused by precision issues when auction length < 1 day. Both the form and the auction contract allow for duration <= 1 min, the calculation should probably reflect that.

**Comment by jpmonettas** [comment]
5b405ce should also remove some of the issues related to price reset
