### ISSUE TITLE
Turning card in Marketplace doesn't work in Firefox

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#111]
In Firefox it won't show back of the card, just flips the image. Interestingly, My Memefolio - Collected works ok, when sell form is on the back. 
![turn-card-bug](https://user-images.githubusercontent.com/3857155/53542308-6c2fb880-3b50-11e9-8b5f-1dfb5237d133.gif)

**Comment by jpmonettas** [comment]
It doesn't look exactly the same as in google chrome but works now. Don't know how to make them identical, maybe @madvas or @fbielejec can give it a shot?

**Comment by fbielejec** [comment]
I'll try.

**Comment by madvas** [comment]
This is how it works now. It's still not quite right, but for now we can consider it sufficient as we have more important stuff to fix for release. Eventually this should be fixed though. 

![meme-card-firefox](https://user-images.githubusercontent.com/3857155/53637788-ad11f500-3c56-11e9-8fd4-9204c5b5665e.gif)
