### ISSUE TITLE
Memefolio - Curated and Dank Registry - Vote has duplicate entries

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#120]
Dank Registry - Vote has triplicated entries (all users see it like this). I discovered why is that as well. After each user voted, new entry has started to be displayed. 1 voter - 1 entry. 2 voters - 2 entries (of same meme), 3 voters - 3 entries. 

![image](https://user-images.githubusercontent.com/3857155/53634386-a9797080-3c4c-11e9-821d-98e24233d5bb.png)

Memefolio - Curated has triplicated entries, but only for challenger's address. Other users see Memefolio - Curated correctly. 
![image](https://user-images.githubusercontent.com/3857155/53634563-0aa14400-3c4d-11e9-8a90-455596ad7dd7.png)

**Comment by fbielejec** [comment]
Same as #108
