### ISSUE TITLE
Vote Reward button not displayed on meme detail page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#125]
Here, vote reward button is displayed
![image](https://user-images.githubusercontent.com/3857155/53710832-af9c6680-3e71-11e9-93dd-8f69a7be53c5.png)
But when going to meme detail, it's not there. Also styling of chart section should be exactly same as in picture above. Text centred and more space between chart and text. This was already correct before, Idk why it's broken again...
![image](https://user-images.githubusercontent.com/3857155/53710846-c93dae00-3e71-11e9-93d6-0240195f9267.png)

**Comment by jpmonettas** [comment]
This was fixed in 332cc66
