### ISSUE TITLE
[QA] Notification feature

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#129]
Pending any kind of onboarding tutorial, I think it will be hard to use the app without a solid notification system guiding people as they get going. Possibly even an initial one prompting them to get some DANK with the faucet.  

**Currently for new people have this experience:**
1. Landing page with activity.  

2. They poke around until they find memes and the registry

3. They find the registry and browse. Clicking a meme is intuitive and first thing they would likely do but it takes a bit to figure out you can click the card name below to see more about the meme.

4.  If they get curious and make it to the Registry and try to submit there is little info on requirements or what that means to submit. 

5. If you do submit, nothing happens. A popup reminding you to claim your vote reward would be nice to have, or email notifications like we have in Name Bazaar with some guiding information. 
for voting periods and claiming. 

Another option could be to land people on the how it works page or do something similar to the [Adchain registry](https://publisher.adchain.com/) in a popup.  

vote, reveal, claim, and issue the memes is all a bit elusive without some notifications.

**Comment by madvas** [comment]
As for no. 4., on each page we have space reserved for explanation. Currently there's just "Lorem" everywhere, this needs to be replaced with instructions. 
![image](https://user-images.githubusercontent.com/3857155/53782698-150b5880-3f41-11e9-8b7a-34b7f176a441.png)
