### ISSUE TITLE
[QA] While a meme is being challenged, the reason should be clearly stated as "reason"

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#130]
The challenge reason could be clearly shown in red with a chat box to discuss. I assume many will want to discuss like they do on the Adchain registry. (May be a longer term feature request after we have the MVP out)  

![desktop](https://user-images.githubusercontent.com/4667076/53763527-4542f080-3e88-11e9-849c-24780de75816.PNG)

**Comment by madvas** [comment]
I agree, text can be made pink color, which we use throughout the app
