### ISSUE TITLE
[QA] "Tag" submission form placeholder overrides entered text 

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#131]
http://qa.district0x.io/#/dankregistry/submit

When using the submission form, the "Title" and "Issuance" placeholders will downsize when selected, and remain downsized if data is entered and the form is deselected.

However, when the "Tags" form has data entered, and then is deselected, the "Tags" title will turn back into the fullsize placeholder, obfuscating the entered text.

<img width="461" alt="screen shot 2019-03-04 at 4 14 57 pm" src="https://user-images.githubusercontent.com/29998350/53763864-cce52b00-3e99-11e9-9d53-49817d7759b6.png">

<img width="438" alt="screen shot 2019-03-04 at 4 15 07 pm" src="https://user-images.githubusercontent.com/29998350/53763863-cce52b00-3e99-11e9-96b4-59beb1144f8e.png">

**Comment by madvas** [comment]
yeah, this wouldn't happen if you pressed enter after each tag. But we can make comma to have same effect as enter key.
