### ISSUE TITLE
[QA] Add tags to challenge, voting, and Meme Details pages

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#132]
Voting tags are a submission parameter, so they should be visible on the challenge and voting pages, so users can challenge/vote against poor or bad tagging.

I also do not see any readout of tags on Meme Details pages, we should make sure they're added there for completeness sake.

**Comment by madvas** [comment]
We display tags on voting pages
![image](https://user-images.githubusercontent.com/3857155/53782590-8dbde500-3f40-11e9-825b-c962e5e0b9a8.png)
On meme detail page, they're in the first section. Not in challenge section though, maybe can be added there as well. 
![image](https://user-images.githubusercontent.com/3857155/53782604-a9c18680-3f40-11e9-885e-ce20db28f7d6.png)

**Comment by Alexand0x** [comment]
Weird, maybe my entries didn't take due to the other issue I posted on? so they appeared untagged
