### ISSUE TITLE
[QA] submit /meme tags field should react to comma and space

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#134]
On the submission page, for the tags field, we should add a note to separate tags by space or comma, whichever applies.

**Comment by Bradymck** [comment]
They are separated by hitting enter FYI.

**Comment by madvas** [comment]
yep, as I pointed out here https://github.com/district0x/memefactory/issues/131#issuecomment-469543179, we can make comma and space to have same effect as enter
