### ISSUE TITLE
[QA] Cancel button is greyed out on 'Submit' page

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#137]
The submit button always remains greyed out.

 ![submit](https://user-images.githubusercontent.com/4667076/53766054-06646900-3e8f-11e9-96f2-651eab29183a.PNG)

**Comment by madvas** [comment]
That's how cancel button is, it's not grayed out, it's clickable. That's how we got it from designers, can be changed though.

**Comment by Bradymck** [comment]
Okay. Not a problem. Just pointing it out. Many of these issues can be closed out at your discretion. Most are minor design decisions

**Comment by jpmonettas** [comment]
Closing since is expected behavior
