### ISSUE TITLE
[QA] Emojis should be restricted in tags/titles

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#138]
Emojis may cause issues with our UX. I guess it's not a big deal, it's more of a UX decision if we should restrict them or not, it may be funny, not sure.  

![emoji](https://user-images.githubusercontent.com/4667076/53766152-52afa900-3e8f-11e9-9c38-70ee590bea03.PNG)

**Comment by madvas** [comment]
maybe I'd allow them for the title, but for tags we can disable.
