### ISSUE TITLE
[QA] Character limit is a bit high on card titles

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#139]
The character limit may be a bit much. Another UX decision. Just added emojis to show/push the limit. 

![emo](https://user-images.githubusercontent.com/4667076/53766357-d8335900-3e8f-11e9-92ed-7ecfeee9e51e.png)

**Comment by Bradymck** [comment]
Have not tried on mobile yet. That would be my biggest worry.

**Comment by madvas** [comment]
Put ellipse for notification text if too long
