### ISSUE TITLE
[QA] Periodic error on vote page

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#140]
I can't easily reproduce this but it seems to happen when I submit a new meme and it makes you miss your reveal and won't let you vote. It shows no errors in console. 

After refreshing page a couple times it finally showed an error that I have not voted. I think this is due to the short voting period on the QA instance. 

![vote](https://user-images.githubusercontent.com/4667076/53767295-99eb6900-3e92-11e9-820c-12702c4a4ff0.PNG)

Will add updates here as I try to reproduce.

**Comment by madvas** [comment]
I confirm, sometimes I get "Secret to reveal vote was not found ..." error, when I shouldn't. Refreshing page fixes it.

**Comment by Bradymck** [comment]
I'm sure we will get users with this experience and want to submit a new issue. I'll leave open just so we don't have to open duplicate issues after going live
