### ISSUE TITLE
[QA] Memes showing in wrong location

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#141]
The 'Created' memes show in 'Collected' section. 
The following meme is one I made and shows in the collected section.
![mememem](https://user-images.githubusercontent.com/4667076/53765376-0e230e00-3e8d-11e9-8e52-b69423f0a74f.PNG)

The memes that failed should be either on a separate tab in 'Curated' or not shown at all if they fail.

**Comment by madvas** [comment]
I think you misunderstood how UI works. After you Issue your meme in Created tab, the meme will show up in your Collected tab, because now you own card you've issued. Therefore you can start selling it.

**Comment by Bradymck** [comment]
This was more of a suggestion but I see what you mean. It's not a big deal really. I'll close this out.
