### ISSUE TITLE
[QA] Unclear failure reason for some images. 

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#142]
I uploaded a larger Gif file and I am almost certain that was the failure reason but I saw no reason and it simply doesn't show transaction window and clears the submission box. 

![annotation 2019-03-04 154036](https://user-images.githubusercontent.com/4667076/53767871-5a258100-3e94-11e9-9bd1-b29ec54b3698.jpg)

**Comment by Bradymck** [comment]
This is the file I attempted 
![ezgif com-optimize 7](https://user-images.githubusercontent.com/4667076/53767984-bdafae80-3e94-11e9-878a-989616440fb6.gif)

**Comment by madvas** [comment]
Put limit for uploaded files 1.5 MB
