### ISSUE TITLE
Replace Lorem placeholders throughout the app

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#151]
We should replace placeholder texts throughout the app. I'm gonna paste here images with reference numbers. @Alexand0x  please comment here for each number what should be placed as a text. @jpmonettas will then implement. 

1. 
![image](https://user-images.githubusercontent.com/3857155/53809601-ae5d5d80-3f87-11e9-9424-f67b05d69dbc.png)

2. 
![image](https://user-images.githubusercontent.com/3857155/53809638-bcab7980-3f87-11e9-866f-fce115f087e1.png)

3. 
![image](https://user-images.githubusercontent.com/3857155/53809697-d6e55780-3f87-11e9-86bb-8a0ff86b7dc8.png)

4. 
![image](https://user-images.githubusercontent.com/3857155/53809727-e4024680-3f87-11e9-82d0-12fe4948dd3a.png)

5.
![image](https://user-images.githubusercontent.com/3857155/53809743-eb295480-3f87-11e9-9177-2ca3c6d5fd71.png)

6. 
![image](https://user-images.githubusercontent.com/3857155/53809786-07c58c80-3f88-11e9-84ef-0bb2b8acb480.png)

7. 
![image](https://user-images.githubusercontent.com/3857155/53809801-114ef480-3f88-11e9-921c-d27abd36c866.png)

8. 
![image](https://user-images.githubusercontent.com/3857155/53809813-1c098980-3f88-11e9-9196-0a1d99a3698d.png)

9. 
![image](https://user-images.githubusercontent.com/3857155/53809830-2461c480-3f88-11e9-85fd-c5fa9c1377bf.png)

10. 
![image](https://user-images.githubusercontent.com/3857155/53809842-2c216900-3f88-11e9-89b0-657c6754f5cd.png)

11. 
![image](https://user-images.githubusercontent.com/3857155/53809872-42c7c000-3f88-11e9-8586-dde567a0aec2.png)

12. 
![image](https://user-images.githubusercontent.com/3857155/53809889-49eece00-3f88-11e9-9734-27cb9ac19678.png)

13. 
![image](https://user-images.githubusercontent.com/3857155/53809900-51ae7280-3f88-11e9-8339-d41d955b504f.png)

14. 
![image](https://user-images.githubusercontent.com/3857155/53809918-5a9f4400-3f88-11e9-881b-2dc14970283d.png)

15. 
![image](https://user-images.githubusercontent.com/3857155/53809928-6428ac00-3f88-11e9-8fb3-3be2d133cc15.png)

16. 
![image](https://user-images.githubusercontent.com/3857155/53809950-70ad0480-3f88-11e9-93be-99040e090db0.png)

17. (not sure if this one can stay or we wanna change)
![image](https://user-images.githubusercontent.com/3857155/53809976-81f61100-3f88-11e9-94e6-583d70e30ea7.png)

18. This one can be different for all stages of challenge. Those are: 
   User can submit challenge
   User can vote 
   User can reveal vote 
   Voting finished, resolved
![image](https://user-images.githubusercontent.com/3857155/53810045-a9e57480-3f88-11e9-9318-29f378e6c57d.png)

19. 
![image](https://user-images.githubusercontent.com/3857155/53810158-f03ad380-3f88-11e9-9db1-ff540efcbb54.png)

**Comment by madvas** [comment]
Cool, thanks for quick reply. Just number 19. is missing please

**Comment by Alexand0x** [comment]
19. **RELATED MEMES**
Similar memes for sale now
