### ISSUE TITLE
Link to Meme Detail page on back of card

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#154]
It's not clear how to get to a Meme's Details page from the marketplace or other views. Add a button/link under 'Buy' button after clicking on a card to flip it around.

**Comment by madvas** [comment]
I'm gonna connect with Griflan what would be the best looking solution for this

**Comment by madvas** [comment]
This should be implemented. The link in top right corner. 
![image](https://user-images.githubusercontent.com/3857155/54065338-1d6dd700-4252-11e9-8d35-6f124eae0764.png)

**Comment by benzap** [comment]
Noticed a few small styling issues with the latest merge that i'll work out within this issue

- border cut off
https://i.imgur.com/mkrA8e1.png

- I think the footer text can be centered better
https://i.imgur.com/5S1y0z5.png

**Comment by benzap** [comment]
Fixed by #198 Merge
