### ISSUE TITLE
[QA] Feature Request - Send function

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#167]
One of the first comments I'm sure we will get from the public is "how to send a meme to a friend or external ETH address." I think we need this for the launch. 

For my side project to help promote MF, I will also need this function. 

I could possibly send an ERC721 on Mycrypto but it would be ideal to have a send button on the back or below each meme card similar to the gift/send feature on other ETH collectible apps.

**Comment by joeyurgz** [comment]
+1

**Comment by jpmonettas** [comment]
@madvas @joeyurgz @Bradymck I can implement this, any ideas on the UI for this? 
Looks like the button should show on my memefolio collecteds, but the back of this is the sell form, which also doesn't have room for a extra button

**Comment by madvas** [comment]
I will discuss with Griflan about this

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/54136413-54104100-444e-11e9-9a52-041f6d431eea.png)
![image](https://user-images.githubusercontent.com/3857155/54136937-460ef000-444f-11e9-9550-3ec1870b630e.png)

**Comment by madvas** [comment]
Ehm, seriously? It's supposed to look like in the picture
* Wrong text
* Missing padding up and down
* Missing underline

![image](https://user-images.githubusercontent.com/3857155/54332138-6dcca680-464f-11e9-99e6-bfc475f88241.png)

**Comment by madvas** [comment]
When trying to send I get 
![image](https://user-images.githubusercontent.com/3857155/54332259-f8ada100-464f-11e9-836d-52f8f9175f72.png)

**Comment by Bradymck** [comment]
Sweet, my secret plans for meme domination can now begin. lol

**Comment by madvas** [comment]
Bottom border made invisible 
![image](https://user-images.githubusercontent.com/3857155/54407700-74235700-4711-11e9-8c52-035109146a3f.png)

**Comment by jpmonettas** [comment]
Fixed style issues, wasn't able to reproduce the metamask error.
