### ISSUE TITLE
Implement Dank Registry Challenge Page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#17]
![dank-registry-challenge](https://user-images.githubusercontent.com/3857155/42194663-e3d1258e-7e29-11e8-8f10-5fa45e0e0efa.jpg)

**Comment by jpmonettas** [comment]
Implemented https://github.com/district0x/memefactory/blob/feature/ui/src/memefactory/ui/dank_registry/challenge_page.cljs
