### ISSUE TITLE
Cards flip and show mirrored text when scrolling

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#170]
When scrolling down any page with numerous memes, the cards briefly flip as if they were clicked and I see the back of card text but mirrored.

**Comment by madvas** [comment]
I confirm this problem. What's happening is, if image is being loaded slowly, it shows flipped back-of-the-card behind the loaded image. 

![image](https://user-images.githubusercontent.com/3857155/54020260-ee0e8a00-41bf-11e9-8e5e-ad5a3cc446fd.png)

**Comment by benzap** [comment]
I'll take a stab at this, I have a new implementation I threw together that should work better between browsers

**Comment by jpmonettas** [comment]
@benzap I'm not sure new implementation can solve this issue since while image is loading you can see whatever rendered first in the back, but maybe I'm wrong.
I think one way to go is to display:none the entire tile until [:img {:on-load ...}], but requires some refactor in a bunch of places

**Comment by benzap** [comment]
@jpmonettas my implementation is completely different from what is available, and doesn't show the backside on initial load, but i'll see if I can reproduce this with the new implementation.

You're probably referring to this, which i'm going to base it off of: https://codepen.io/benzap/pen/RdGroe?editors=0100

latest version does include display:none in the correct places for the animation keyframe, but there are additional changes i'll have to consider as well.

**Comment by benzap** [comment]
Related to #111
