### ISSUE TITLE
Fix conditions to display spinner throughout the app

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#173]
In last [update](https://github.com/district0x/district-ui-graphql/commit/b3edfa9ab90257835a18ed274d60dc31c19ee7f7) of district-ui-graphql (1.0.9), the module is recognising preprocessing phase of a query, so `:graphql/loading?` is `true` already on first render of component. Therefore we're no longer forced to render old results of query on first render of a component, simply because we can put condition to not render them if loading? is true. 

In https://github.com/district0x/memefactory/commit/c103f1bcc61b9de5d162b07bc5a6b93acdf4b982 for MF I demonstrated how condition for loading spinner should be fixed everywhere. 

Before, we were doing: 
```clojure
[list-of-items]
(when loading?
   [spinner])
```
What we want now is: 
```clojure
(if loading?
   [spinner]
   [list-of-items])
```
For all spinners throughout the app

**Comment by jpmonettas** [comment]
@madvas how will that achieve the spinner effect when you have multiple pages and you want the spinner only for the "loading row" while still seeing the rest of the content?

**Comment by madvas** [comment]
Okay so, as @jpmonettas pointed out, there was a mistake in my original approach, in which infinite scroll wouldn't work. In this commit https://github.com/district0x/memefactory/commit/14a708578b2855ed3960a39024058dd465d1ef3f I pushed another approach, which seems to work correctly with infinite scroll as well. 

So pseudocode for spinner goes like this: 
```clojure
(if (and (empty? all-items))
         (not (:graphql/loading? (last @query-results)))
  [no-items]
  (when-not (:graphql/loading? (first @query-results))
     [items-list]))
(when (:graphql/loading? (last @query-results))
     [spinner])
```

**Comment by jpmonettas** [comment]
Applied that to marketplace, all leaderboards pages and all memefolio tabs
