### ISSUE TITLE
Infinite scroll needs improvement

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#179]
So what happens is this: Page loads 6 memes at the time. As you can see, on the first scroll down, another 6 is correctly loaded and appended towards bottom of the page, so user can continue scroll. But after that, when another 6 is loaded, although they're still added to a list, user's scrolling position stays at the bottom, so it triggers another load right after that. And in this way 3 more loads under loading of all items is finished. Correctly it should work, like it worked for first load: Items get loaded and user can keep scrolling to the bottom. 

![infinite-scroll-bug](https://user-images.githubusercontent.com/3857155/54099625-ca7c5700-43ec-11e9-9576-869231b0dd3a.gif)

**Comment by jpmonettas** [comment]
I spent some time with this and seems related to the calculations in should-load-more? in the infinite-scroll component https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/components/infinite_scroll.cljs#L38

Maybe @fbielejec has a better idea of those calculations so assigning to him.

**Comment by benzap** [comment]
@fbielejec If you have too much on your plate, I could take a stab at fixing up the implementation. Was looking over the code and I had some ideas on improvements

**Comment by fbielejec** [comment]
I'm afk till Thursday, if you have nothing else please feel free, else i'll
fix when i'm back :)

**Comment by benzap** [comment]
Unless anything else comes up beginning of next week, i'll assign this to myself. Enjoy your hike!

**Comment by fbielejec** [comment]
I'll take it over, I have some ideas I'd like to try.

**Comment by madvas** [comment]
Nope, still not working properly. Just try to go to http://qa.district0x.io/dankregistry/browse and try to go to the bottom

**Comment by benzap** [comment]
Important to note that when I fixed it up, the problem only persisted when I was using Chrome/Firefox on Windows, and the problem didn't exist while testing it on linux. So there are definitely irregularities between how the different platforms are handling scroll, especially when new elements are added at the bottom of a div while scrolled to the bottom.

You'd think that in 2019, we'd be past these browser incompatibility issues, but I guess not 😖

**Comment by madvas** [comment]
I'm buying 5 beers to whomever can solve this already

**Comment by joeyurgz** [comment]
On marketplace page, after scrolling down a bit, the page gets stuck sort of on the bottom (appears blank, no cards showing), and I am unable to scroll back up.

**Comment by fbielejec** [comment]
this issue is  unfortunately a bit more complex, but i'm working on an
overhaul of the way we pull and display new data.
