### ISSUE TITLE
Implement Dank Registry Vote Page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#18]
![dank-registry-vote](https://user-images.githubusercontent.com/3857155/42194756-5a3f644c-7e2a-11e8-9106-6155b0f295c2.jpg)
![dank-registry-vote-resolved](https://user-images.githubusercontent.com/3857155/42194755-5a257f3c-7e2a-11e8-8889-9394dd5b6bd6.jpg)

**Comment by jpmonettas** [comment]
Implemented https://github.com/district0x/memefactory/blob/feature/ui/src/memefactory/ui/dank_registry/vote_page.cljs
