### ISSUE TITLE
[QA] Broken icon 

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#187]
Looks like font issues:

![2019-03-13-1552476015_screenshot_3286x1080](https://user-images.githubusercontent.com/468572/54275263-7b6c2880-458a-11e9-82d3-4069bd46f40e.jpg)

**Comment by jpmonettas** [comment]
Could not reproduce in any of the scenarios I tried

![latest-screenshot](https://user-images.githubusercontent.com/786299/54433994-fad53580-470b-11e9-9ec6-9d25f2f8dc86.png)
