### ISSUE TITLE
State the card dimensions on the create/submit page

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#190]
The submit meme page should say what dimension card size we use so users know what size image to upload. Should also note that the image will be compressed to fit the dimensions if not sized properly.

**Comment by jpmonettas** [comment]
@madvas we need designers input for this one

**Comment by madvas** [comment]
Just put within this area, with color `#47608e`. Of course put reasonable padding between text and button and gray area. 
![image](https://user-images.githubusercontent.com/3857155/54357812-76de6780-4691-11e9-95b8-c7ef124d8fdb.png)
