### ISSUE TITLE
Resizes upload Image to a distorted level

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#191]
Resizes the image 
<img width="1236" alt="resized" src="https://user-images.githubusercontent.com/31779808/54307819-d0f40580-4589-11e9-8ea3-958c6319783a.png">

**Comment by jpmonettas** [comment]
I think there was a voting and card aspect ratio was decided to be height=width*1.5
Looks like we are going to state accepted dimensions in that screen, see #190

**Comment by pmr212** [comment]
Sounds good, I will close this issue and revert to the solution on #190
