### ISSUE TITLE
Gas not calculating correctly when starting sale

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#192]
Tried to start a sale for 10 newly issued cards 3 times, each failed due to insufficient gas (it was calculating/using a gas limit of 6000000). After manually adjusting the gas limit to 8000000 it worked.

**Comment by jpmonettas** [comment]
@madvas should we remove all :gas opts in all UI :tx-opts to let metamask do the calculation?

**Comment by madvas** [comment]
yes
