### ISSUE TITLE
Title text cut off when too long

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#193]
Meme title text is cut off awkwardly at a certain length, see image

<img width="1437" alt="Screen Shot 2019-03-13 at 12 29 06 PM" src="https://user-images.githubusercontent.com/16138359/54308627-9e4b0c80-458b-11e9-89c9-2b4bdd003ebc.png">

**Comment by jpmonettas** [comment]
Looks like this now :
![latest-screenshot](https://user-images.githubusercontent.com/786299/54309538-1b3bad80-45af-11e9-81d2-8dd14d43ab1e.png)
