### ISSUE TITLE
Should say "Claim Vote Reward" instead of "Vote Reward"

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#194]
On the transaction log it says it correctly - "claim vote reward" but the actual button only says "vote reward"

<img width="1012" alt="should say claim vote reward" src="https://user-images.githubusercontent.com/31779808/54309585-aefc8200-458d-11e9-9dd3-199f2c05eb9c.png">

**Comment by jpmonettas** [comment]
I think that was changed back because the full text doesn't fit nicely on the button

**Comment by benzap** [comment]
A good middle ground, just "Claim Reward"?

**Comment by benzap** [comment]
Once and if there is a DANK token logo, we could put "Claim () Reward"

**Comment by madvas** [comment]
Actually, good idea @benzap. We gonna try to do that

**Comment by madvas** [comment]
So let's try this. But first probably paste here screen how it looks before pushing

[dank-logo.zip](https://github.com/district0x/memefactory/files/2969494/dank-logo.zip)

**Comment by benzap** [comment]
@madvas, just caught your message. You can see an example of it in the PR
https://github.com/district0x/memefactory/pull/215
