### ISSUE TITLE
"Reclaim Vote" button available even if Meme was voted Stank

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#195]
My meme was voted Stank. And now you add insult to injury by allowing me to burn more gas trying to collect Dank that will inevitably get rejected. I don't think this option should be there. 
<img width="1047" alt="Reclaim votes for rejected meme" src="https://user-images.githubusercontent.com/31779808/54310867-9b9ee600-4590-11e9-970c-f4c47a787e80.png">

**Comment by jpmonettas** [comment]
@pmr212 that doesn't mean vote reward, that should be showing as a way to collect you dank votes stake  if you missed the reveal period

**Comment by pmr212** [comment]
Ahh I see. But I didn't have any votes to reclaim, so should I still be allowed to use that button? Is there a way to only make it available if there is DANK to be reclaimed somehow?

**Comment by jpmonettas** [comment]
Oh if you didn't participate in voting then it is a bug, it shouldn't be showing

**Comment by benzap** [comment]
I can take a stab at this and #194
