### ISSUE TITLE
Smart Contract tests

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#2]
Write Clojurescript tests for Memefactory smart-contracts. Test environment has been already pre-setup [here](https://github.com/district0x/memefactory/tree/master/test/memefactory/tests/smart_contracts).

To run tests on file changes run `lein test-dev`

Following scenarios should be tested: 

### RegistryEntry
RegistryEntry is base class for either Meme or ParamChange. Not supposed to be deployed by itself, so for testing you can be creating Meme contracts and test RegistryEntry methods that way. 

#### `construct`
Call `meme-factory/approve-and-create-meme`
* Can create RegistryEntry (as Meme) with valid parameters
* Created RegistryEntry has properties initialised as they should be: 
   * `deposit` has correct value (same as deposit parameter value)
   * balance of `registryToken` on RegistryEntry contract equals to deposit
   * has correct `creator`
   * has correct `version`
* `construct` method of cannot be called twice 

#### `createChallenge`
Call `registry-entry/approve-and-create-challenge`
* Can create challenge under valid condidtions
* Check properties of created challenge: 
   * `registryToken` deposit was transferred from challenger to RegistryEntry contract
   * has correct `challenge.challenger`
   * has non-empty `challenge.votingToken`
   * `challenge.votingToken` has `controller` set to dead address `0x0`
   * has correct `challenge.voteQuorum`, `challenge.commitPeriodEnd`, `challenge.revealPeriodEnd`, `challenge.rewardPool`, `challenge.metaHash`
* Challenge cannot be created outside challenge period
* Challenge cannot be created is RegistryEntry was already challenged

#### `commitVote`
Call `registry-entry/approve-and-commit-vote`
* Vote can be committed under valid conditions
* Check properties of committed vote: 
  * `challenge.votingToken` amount was correctly transferred from voter to RegistryEntry contract
  * has correct `challenge.vote[_voter].secretHash`, `challenge.vote[_voter].amount`
* Vote cannot be committed outside vote commit period 

#### `revealVote`
Call `registry-entry/reveal-vote`
* Vote can be revealed under valid conditions
* Check properties of revealed vote: 
  * has correct `challenge.vote[msg.sender].revealedOn` (roughly), `challenge.vote[msg.sender].option`
* Test both scenarios for vote options and check for correct `challenge.votesFor` and `challenge.votesAgainst`
* Vote cannot be revealed outside vote reveal period
* Vote cannot be revealed with incorrect salt 
* Vote cannot be revealed twice

#### `claimVoteReward`
Call `registry-entry/claim-vote-reward`
* Vote reward can be claimed under valid condidtions
* Check properties of claimed vote: 
   * `registryToken` reward was correctly transferred from RegistryEntry to voter
   * has correct `challenge.vote[_voter].claimedRewardOn` (roughly)
* Cannot be called before reveal period is over
* Cannot be called twice 
* Throws error when claiming reward for vote option that didn't win 

#### `claimChallengeReward`
Call `registry-entry/claim-challenge-reward`
* Challenge reward can be claimed under valid conditions
* Check properties of claimed reward:
   * `registryToken` reward was correctly transferred from RegistryEntry to challenger
   * has correct `challenge.claimedRewardOn` (roughly)
* Reward cannot be claimed twice
* Reward can be claimed only if `VoteOption.VoteFor` has won

Rest of constant methods can be tested while testing scenarios above, just slip them in where it's appropriate. 

#### `construct`
Call `meme-factory/approve-and-create-meme`
* Meme can be created under valid conditions
* Check properties of claimed reward:
  * has correct `metaHash`, `totalSupply`
* Cannot create meme with higher supply than `maxTotalSupply` TCR param

#### `transferDeposit`
Call `meme/transfer-deposit`
* Meme deposit can be transferred from whitelisted meme to `depositCollector` address
* Meme deposit can't be transferred if meme was challenged

#### `mint`
Call `meme/mint`
* Meme tokens can be minted under valid conditions
* Check properties of after minting collectibles:
   * Meme contract has correct `totalMinted`
   * Meme creator is owner of newly minted tokenIds 
* test mint function with passed amount that's bigger than totalSupply or similar edge cases
* mint function cannot be called when registry entry is not whitelisted

### `onERC721Received`
Call `meme-token/transfer-multi-and-start-auction`
* Creates MemeAuction under valid conditions
* Check properties after creating MemeAuction:
   * Created MemeAuction has correct: `seller`, `tokenId`, `startPrice`, `endPrice`, `duration`, `startedOn`
* `onERC721Received` fails when called directly, without transferring tokenId
* fails when passed `duration` is bigger than `:max-duration` TCR parameter or shorter than 1 minute

### `fireMemeAuctionEvent`
* Cannot be called directly, only by MemeAuction contract

### `buy`
Call `meme-auction/buy`
* Buys token collectible under valid conditions
* Check properties after buying:
  * buyer is new owner of tokenId
  * seller received funds minus cut
  * memeAuctionCutCollector received the cut
  * Extra funds sent to `buy` method are sent back to the buyer
* Meme cannot be bought if not enough funds is sent

### `cancel`
Call `meme-auction/cancel`
* Cancels auction under valid conditions
* Check properties after canceling:
  * seller is owner of the tokenId again
* Cannot be canceled by anybody except the seller  

#### `computeCurrentPrice`
Call `meme/compute-current-price`
* Correctly calculates reverse-auction price 

#### `construct`
Call `param-change-factory/approve-and-create-param-change`
* Can create challenge under valid condidtions
* Check properties after creating param change:
  * has correct `db`, `key`, `value`, `valueType`, `originalValue`

#### `applyChange`
Call `param-change-registry/apply-param-change`
* Param change can be applied under valid conditions
* Check properties after applying param change:
   * `db` really has changed value under the `key`
   * has correct `appliedOn` (roughly)
* Cannot be applied if original value is not current value 
* Cannot be applied twice 
* Cannot be applied when not whitelisted 

#### `setFactory`
Call `registry/set-factory`
* Can be called under valid conditions 
* Unauthorised address cannot call this method 

#### `addRegistryEntry`
* Cannot be called by regular address

#### `setEmergency`
* Can be called by authorised person
* After enabling emergency, check at least 1 method in a RegistryEntry with `notEmergency` modifier, if it starts failing
* Unauthorised address cannot call this method 

### `MutableForwarder`
Call `mutable-forwarder/replace-target` (not created at the moment)
Both `:meme-registry-fwd` and `:param-change-registry-fwd` are deployed as `MutableForwarder` contracts so we can update them with bug fixes & new features while preserving their address. 

#### `setTarget`
Test if we can replace target with new address and the contract will still works. 

That's it! You can peek into [NameBazaar tests](https://github.com/district0x/name-bazaar/tree/master/test/server/name_bazaar) for inspiration. More importantly, I might have forgotten something, so while writing tests, please use your own brain and "hacker" mindset and think how contracts could be potentially hacked.

**Comment by jpmonettas** [comment]
Tests has been implemented in : 

- /test/memefactory/tests/smart_contracts/registry_entry_tests.cljs
- /test/memefactory/tests/smart_contracts/meme_tests.cljs
- /test/memefactory/tests/smart_contracts/meme_auction_tests.cljs
- /test/memefactory/tests/smart_contracts/param_change_tests.cljs
- /test/memefactory/tests/smart_contracts/registry_tests.cljs
