### ISSUE TITLE
Implement Meme Detail Page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#20]
![memefolio-detail1](https://user-images.githubusercontent.com/3857155/42194867-dd65c5f0-7e2a-11e8-95e1-16e596a3ca38.jpg)
![memefolio-detail2](https://user-images.githubusercontent.com/3857155/42194868-dd7c912c-7e2a-11e8-9e29-d199d4472db9.jpg)
![memefolio-detail3](https://user-images.githubusercontent.com/3857155/42194869-dd966b74-7e2a-11e8-9f5a-a4deed1f8624.jpg)
![memefolio-detail4](https://user-images.githubusercontent.com/3857155/42194870-ddab3342-7e2a-11e8-967a-ac101a01daff.jpg)
![memfolio-detail5](https://user-images.githubusercontent.com/3857155/42194871-ddccd2f4-7e2a-11e8-8393-21ea7395994e.jpg)

**Comment by fbielejec** [comment]
implemented
