### ISSUE TITLE
Replace Lorem placeholder

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#211]
We have one more forgotten lorem, @Alexand0x please give us texts, and then somebody from devs will replace. 

So over here at Meme Detail Page, we have Lorem under a meme status. The text should be describing the status a meme is in. Possible statuses are: 
* In Registry
* Rejected
* In Challenge Period
* Challenged

For each status, there should be different text. 

![image](https://user-images.githubusercontent.com/3857155/54444106-a5813e80-4774-11e9-8dd4-d221e88a89f6.png)

EDIT: 
Found one more Lorem, over here: 
![image](https://user-images.githubusercontent.com/3857155/54505667-5f420000-496b-11e9-819f-917708c59a45.png)
There can be some short note, something like: Vote for DANK in order for meme to get into registry, vote for STANK to reject it. 

Here's one more: 
![image](https://user-images.githubusercontent.com/3857155/54505912-9e248580-496c-11e9-9894-f3b866a6fe3e.png)

**Comment by Alexand0x** [comment]
> Meme Detail Status:

In Registry -> **In Registry**
_This meme has passed through the challenge phase and has been placed into the Dank Registry._

Rejected -> **Rejected from Registry**
_This meme was challenged and lost. It's ineligible for the Dank Registry unless resubmitted._

In Challenge Period -> **Open for Challenge**
_This meme has been submitted to the Dank Registry, but is still open to be challenged. The challenge window closes in [XX:YY:ZZ]_

Challenged -> **Challenged**
_This meme has had its status in the registry challenged. It will be either accepted or rejected when the vote and reveal phases conclude in [XX:YY:ZZ]_

> Challenge vote flavor text:

_Below you can choose to vote "Dank" to include the Meme in the registry or "Stank" to reject it. You can enter the amount of DANK tokens to commit to this vote._
[Buttons] [Buttons]
_You can vote with up to [XX] DANK. Your tokens will be returned to you after revealing your vote._

> Challenge reveal timer

_This meme has been challenged and voting has concluded. You can reveal any votes you made with the button below, before time runs out on the reveal period._

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/54661579-630d8800-4b0d-11e9-9987-36709948ebee.png)

Forgot to change those status titles as Alexander wrote:
Rejected should change to Rejected from Registry

![image](https://user-images.githubusercontent.com/3857155/54661591-715ba400-4b0d-11e9-9f24-47c1397f73cf.png)
