### ISSUE TITLE
Make challenge comment pink

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#218]
Please make the comment pink
![image](https://user-images.githubusercontent.com/3857155/54505732-b516a800-496b-11e9-8797-8f18fe028226.png)
Same as we have here: 

![image](https://user-images.githubusercontent.com/3857155/54505726-acbe6d00-496b-11e9-8c01-0157f901755c.png)

**Comment by benzap** [comment]
Fixing in #219
