### ISSUE TITLE
Add DANK logo to all Get Dank buttons

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#219]
We can add DANK logo http://qa.district0x.io/assets/icons/dank-logo.svg to all GET DANK buttons. We'll put between "GET DANK" and the arrow, so: 
GET DANK [logo] -> 

Please post screenshot first, for approval 

![image](https://user-images.githubusercontent.com/3857155/54506250-38d19400-496e-11e9-8161-cdb97ca5acc6.png)

**Comment by benzap** [comment]
@madvas here's what I have

![dank-logo](https://i.imgur.com/mUzlAAw.png)

**Comment by benzap** [comment]
@madvas, should I increase the size of the text?

![dank-bigger](https://i.imgur.com/jozZE02.png)

**Comment by madvas** [comment]
Should decrease icon size

**Comment by benzap** [comment]
Latest Revision

![latest](https://i.imgur.com/KhRG87Q.png)

**Comment by madvas** [comment]
Arrow is not in the middle. Also please decrease both font-size and icon-size

**Comment by benzap** [comment]
Fixed the arrow, made it a bit bigger, made the text and logo smaller

![get-dank-button](https://i.imgur.com/slt8yfE.png)

**Comment by benzap** [comment]
bump @madvas

**Comment by madvas** [comment]
Cool, this is good to go 👍
