### ISSUE TITLE
Buttons to claim rewards are missing

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#220]
![image](https://user-images.githubusercontent.com/3857155/54506638-045ed780-4970-11e9-8d57-de2452782ed7.png)

**Comment by benzap** [comment]
I wonder if this all started once I made this change

https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/components/buttons.cljs#L26

**Comment by jpmonettas** [comment]
@madvas @benzap I couldn't reproduce this.
The only issue I'm seeing is when the new look, both challenge and votes rewards have the same text, with different colour, which is confusing.

![latest-screenshot](https://user-images.githubusercontent.com/786299/54557048-0d17d380-4999-11e9-9658-0ce0755ef8b8.png)

**Comment by benzap** [comment]
@jpmonettas @madvas I guess we should just be on the lookout for whether maybe it's just delayed syncing issues, or maybe caching issues when viewing the latest QA. I did happen to see the same thing, so it could be a build issue

**Comment by madvas** [comment]
To me it still doesn't show the buttons, I tried to clear browser data. Buy yeah, same text just different color doesn't make sense. That needs to be changed.

**Comment by madvas** [comment]
From further testing I'm deducing the buttons are showed only when active address is challenger. Which explains why it's working for @jpmonettas as well. 

![image](https://user-images.githubusercontent.com/3857155/54582422-3c831a80-4a43-11e9-9d72-9b86b240bb0c.png)
