### ISSUE TITLE
Issuing 2 memes at once messed things up

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#222]
http://qa.district0x.io/memefolio/0x4c3f13898913f15f12f902d6480178484063a6fb/?tab=created

Tried to issue those 2 memes at once. It said both txes went ok, but I can find one first one in Collected tab. Also, as you can see issue button didn't get disabled for the second one. Tried to issue again, but tx is failing. My guess is that something messes up when trying to issue multiple memes, before tx of previous one is processed. 

![image](https://user-images.githubusercontent.com/3857155/54506866-302e8d00-4971-11e9-96ee-1568e0a1ac3b.png)

![image](https://user-images.githubusercontent.com/3857155/54506987-c06cd200-4971-11e9-9365-4c2df4917080.png)

https://ropsten.etherscan.io/tx/0x0f97ee1a3eec08e27a6b55437b13023dacba194c659435c10807426d8c9a1c4a
https://ropsten.etherscan.io/tx/0xb052e7b90604790215d1c7a364916d87212d46e8099b1c80917c92177e556eaa
https://ropsten.etherscan.io/tx/0x95a6800c3fc8d1379097105b01f96416a8ddf76d835f4bc1f45600723e87c131

**Comment by jpmonettas** [comment]
@madvas I couldn't reproduce this. I tried a couple of combinations in QA and ganache -b 15, getting both transactions in pending state and then both corrects, with everything working fine. 
Also tried to submit a couple of memes very quickly, haven't found any issue.
