### ISSUE TITLE
DEV: Add semantic-ui to .gitignore file, or vbump?

### ISSUE THREAD

**Issue by benzap** [district0x/memefactory#227]
I'm constantly plagued with semantic-ui files that are taking over my git unstaged and untracked areas.

![a](https://i.imgur.com/HElNwSs.png)

Is it possible that i'm pulling in a newer version that's overriding what's already there? It's a lot of files that I need to worry about that i'm worried i'll accidentally pull into one of my commits

**Comment by jpmonettas** [comment]
That is weird, we are not even using semantic ui in memefactory. 
I see Mike added that folder at the beginning of the project, but we should be able to remove it without any issues.

**Comment by benzap** [comment]
Okay, i'll try removing it then. `lein deps` pulls in the semantic stuff, which is why my environment kept getting populated

**Comment by benzap** [comment]
So the project is still using semantic-ui as seen [here](https://github.com/district0x/memefactory/blob/master/resources/public/index.html#L13)

I tried commenting it out to see how it affected the styling, and it still seems to play a role in a few minor areas. @madvas, if you want I could try and replicate the styling and fix the parts that semantic-ui is affecting, and tear it out of the memefactory repository.

**Comment by benzap** [comment]
I think there's still a hook in `lein deps` which is causing it to run. Maybe i'll remove that as an issue fix

**Comment by madvas** [comment]
So this can be closed?

**Comment by benzap** [comment]
This can probably be closed till we discuss it more, i'll bring it up in the next dev meeting
