### ISSUE TITLE
Email templates issues

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#233]
#### 1. Meme Challenged notification
![image](https://user-images.githubusercontent.com/3857155/54584303-8a9b1c80-4a49-11e9-97a6-8db6999068d3.png)

* "Inspired by..." text should be replaced by the new one we have on the page
* Change title to: [meme-title] challenged!
* Change main text to: "Your meme [meme-title] was just challenged. Hurry, you have [minutes remaining] minutes to visit the website and vote to keep your meme in the Dank Registry!"
* Button should say "Vote Now"
* Ideally, we want to display the meme image under the text. Not sure how difficult this would be. 
* Unsubscribe button doesn't work
---

#### 2. Receiving vote reward notification
![image](https://user-images.githubusercontent.com/3857155/54584832-0184e500-4a4b-11e9-9ef4-818e540f7f1a.png)
* Broken templating
* Amount displayed in wei
* Null for meme title
* Headline text: Vote Reward
* Content text: You received [amount] DANK as a reward for voting [DANK/STANK] for [meme-title]
* Button text: My Memefolio
* The button should take to My Memefolio - Curated
* Display meme image under the text

#### 3. Receiving challenge reward notification
![image](https://user-images.githubusercontent.com/3857155/54585089-ba4b2400-4a4b-11e9-8477-351204edb928.png)
* Amount displayed in wei
* Headline text: Challenge Reward
* Content text: You received [amount] DANK as a reward for challenging [meme-title]
* Button text: My Memefolio
* The button should take to My Memefolio - Curated
* Display meme image under the text

**Comment by madvas** [comment]
### 1. Challenge email
* 2 white stripes in header section 
* Using header text "A decentralized registry.." as an image is not such a good idea, because it looks like garbage. Please use it as a text, even if we don't have that font there. 
* Time is missing actual time. But preferably we want to show minutes remaining (like I wrote before), since we don't need to deal with time zones. Time in wrong timezone won't say much to a user. 
* Vote Now button is overflowing
* Image should be clickable too, taking to same page as Vote Now button 
* Twitter leads to district0x, should lead to https://twitter.com/memefactory0x
* Github link should lead to https://github.com/district0x/memefactory
![image](https://user-images.githubusercontent.com/3857155/55057762-af703f00-509c-11e9-8fb3-abca2c17dbd7.png)

### 2. Vote reward email
* Says "DNT" instead of "DANK"
* Amount shown in wei 
* Missing "." at the end of the sentence
* 2 white stripes in header section 
* My Memefolio button is overflowing
* Image should be clickable too, taking to same page as My Memefolio button 
![image](https://user-images.githubusercontent.com/3857155/55058292-1b9f7280-509e-11e9-9940-364d0149095c.png)

### 3. Challenge reward email
* Same issues as vote reward

![image](https://user-images.githubusercontent.com/3857155/55058416-76d16500-509e-11e9-8941-a9c87781fcbe.png)

**Comment by fbielejec** [comment]
Question regarding time - not sure if showing remaining time is a good idea, since emails are not read instantaneously?

**Comment by madvas** [comment]
yeah, but I think still better solution, because we have no information what timezone is user at

**Comment by madvas** [comment]
Button still asks for little bit more love 

![image](https://user-images.githubusercontent.com/3857155/55229816-99a37b00-5250-11e9-8256-4b318f9d2e4c.png)

**Comment by madvas** [comment]
Update main text to: 
"Your offering of [meme-title] was bought for [price] ETH by [buyer-address]."

Buyer address will be linking to his Memefolio - Collected. 

![image](https://user-images.githubusercontent.com/3857155/55314074-86ccb880-5493-11e9-9592-cdc4c2412d5a.png)

**Comment by madvas** [comment]
All numbers should be rounded to 3 decimal places. 

![image](https://user-images.githubusercontent.com/3857155/55457955-bacfe700-5615-11e9-864b-0e4b030c284e.png)

**Comment by madvas** [comment]
Sender of the email should be noreply@memefactory.io
![image](https://user-images.githubusercontent.com/3857155/55460217-98d96300-561b-11e9-8162-6f7160b1f87d.png)

**Comment by benzap** [comment]
Stealing off you @fbielejec

**Comment by fbielejec** [comment]
Go for it :)
