### ISSUE TITLE
No items found is not vertically in the middle

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#237]
I've mentioned it several times already, let's please stop using padding/margin for vertical aligning. We should be using flex or CSS Grid for this. If there is some reason why flex cannot be used, let me know. 

![image](https://user-images.githubusercontent.com/3857155/54659309-df9b6900-4b03-11e9-88e1-ce087bc366bf.png)

**Comment by jpmonettas** [comment]
@madvas I'm using flex or CSS grid when the solution is simple, in this case we need to change the parent display configuration and other properties just to vertically align the no items found. I know it sometimes doesn't look perfect but with a padding-top we can make no-items-found a component from structure and style point of view, without modifying each parent style also.
If you think it is important I can try to do it anyway.

**Comment by madvas** [comment]
Tried to play around that, you're right, looks like quite a lot of work right now, due to variety of parent components. We have more important stuff on the plate, so closing this issue for now. Thanks
