### ISSUE TITLE
Replace "DANK" with dank logo

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#239]
In following places: 

![image](https://user-images.githubusercontent.com/3857155/54659905-854fd780-4b06-11e9-8b3a-097b9143307c.png)
---
![image](https://user-images.githubusercontent.com/3857155/54659915-8e40a900-4b06-11e9-9405-938c05249954.png)
---
![image](https://user-images.githubusercontent.com/3857155/54659920-9862a780-4b06-11e9-8914-82d62eb0d308.png)
---
![image](https://user-images.githubusercontent.com/3857155/54659949-b8926680-4b06-11e9-90a8-5469825f3dec.png)
- in inputs, not button
---
![image](https://user-images.githubusercontent.com/3857155/54659991-f0011300-4b06-11e9-8e21-2e376b9c07b6.png)
- in inputs, not button
----
![image](https://user-images.githubusercontent.com/3857155/54660088-761d5980-4b07-11e9-96bf-b445aa59b119.png)
- all 3 places
---
![image](https://user-images.githubusercontent.com/3857155/54660146-bed51280-4b07-11e9-9207-d630328d0de8.png)
- Replace menu icon, not the word "DANK"
---
![image](https://user-images.githubusercontent.com/3857155/54734125-1f2f8700-4bd0-11e9-92af-f7dc416ee80f.png)

**Comment by jpmonettas** [comment]
@madvas for the menu we need a pink version of the logo, we have been using two versions for each logo.

**Comment by madvas** [comment]
You can user normal version of logo there. 

## Change Color & Styling
Please change color of icon background and title here from orange to purple. 
And make styling of icon following: 
![image](https://user-images.githubusercontent.com/3857155/55055845-e5aac000-5096-11e9-8883-d2b8f011f9e7.png)
![image](https://user-images.githubusercontent.com/3857155/55055823-cdd33c00-5096-11e9-99bf-5e350e347fe6.png)


## Rollback
Please rollback those changes, it didn't really come out as I expected, my bad. 

### 1.
![image](https://user-images.githubusercontent.com/3857155/55055369-551fb000-5095-11e9-8d91-6564fe19d2fe.png)
---
### 2.
![image](https://user-images.githubusercontent.com/3857155/55055389-5fda4500-5095-11e9-9ab5-41908d3fbe0b.png)
---
### 3.
![image](https://user-images.githubusercontent.com/3857155/55055442-839d8b00-5095-11e9-9724-48fbb45b42c4.png)
