### ISSUE TITLE
Some wrong merge? 

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#240]
I don't know if something merged wrongly or something, but when going to Dankest Memes, I'm missing lines added in https://github.com/district0x/memefactory/issues/210 and also there's purple footer that's been removed before. 

![image](https://user-images.githubusercontent.com/3857155/54661143-a5ce6080-4b0b-11e9-869a-cc4f2ff79cb8.png)

EDIT: Purple footer appeared again in Memefolio - Sold 
![image](https://user-images.githubusercontent.com/3857155/54662090-5be77980-4b0f-11e9-83d0-4353135165ab.png)

EDIT: Well, even more weirdness, now it started showing for one card, so I suspect those numbers start to show up when they're more than 0. This is not desired behaviour. Lines should be showing even when numbers are 0. 

![image](https://user-images.githubusercontent.com/3857155/54662299-2a22e280-4b10-11e9-8573-25a60feb0c47.png)

**Comment by jpmonettas** [comment]
Yeah, the entire commit dissapeared :man_shrugging:

**Comment by benzap** [comment]
*hides in a corner*

**Comment by jpmonettas** [comment]
Just went and reaplied it 622f443
