### ISSUE TITLE
Memefolio - Sold incomplete info back-of-the-card

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#268]
Go to http://qa.district0x.io/memefolio/0xc4e0b92df2de77c077d060e49ec63dc196980716?tab=sold

You'll see 2 cards have incomplete info on the back-of-the-card
I've noticed it only on this one page, not sure how would you replicate this locally.

![image](https://user-images.githubusercontent.com/3857155/54895502-7300df80-4ef2-11e9-9c54-d9bc3b32bcae.png)

EDIT: Switching pages back and forth, the same page started showing those 2 empty memes
![image](https://user-images.githubusercontent.com/3857155/54895623-033f2480-4ef3-11e9-9ca8-3d8bc6a872e0.png)

**Comment by jpmonettas** [comment]
We can't reproduce locally, we decided to wait if it happens again. Will reopen if necessary.
