### ISSUE TITLE
Implement DANK faucet with phone number KYC

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#28]
To bootstrap the website more quickly, we'll implement faucet where users can get DANK token for free. To prevent abuse, users will need to verify their phone number in order to get tokens. 

There should be simple contract that does following: 

1. Uses [Oraclize](http://www.oraclize.it/) to make request outside blockchain to check if given phone number was verified. Request would be preferably to 3rd party service. 

2. Deployer of the contract is allowed to change amount of sent tokens per phone number. Also is allowed to claim outstanding tokens, which are in the contract. 

We want preferably offload whole phone verification to a 3rd party service, so our servers don't have to deal with this at all. Parsing server response in Solidity can be quite tricky, so if any service is not returning response in format we can parse in Solidity, we might need to put our server in the middle in the worst case. Oraclize provides some examples on how to parse certain responses. Making research about most suitable service is part of this issue.

**Comment by danielglauser** [comment]
@madvas Please have a look at the faucet in QA and let me know if you see any issues.

**Comment by madvas** [comment]
Hey, worked okay for me. I've opened few minor issues related to faucet. Just one thing I wanna ask, so first time I tried, everything went well, I got DANK. I tried then second time, all submissions went through okay, but I didn't receive any DANK. So is this because there's currently limitation 1 number 1 request? If that's so, we should display it in UI.

**Comment by danielglauser** [comment]
You are correct, that's exactly what happened. Ideally we shouldn't let the user make a second request. I'll see if I can roll that in as a top priority.

**Comment by danielglauser** [comment]
@madvas Is there anything left to do on the faucet?

**Comment by madvas** [comment]
I think we're all good here, closing.
