### ISSUE TITLE
When creating an offer, 'Cancel' button shouldn't be washed out

### ISSUE THREAD

**Issue by benzap** [district0x/memefactory#283]
Feel like the styling on the cancel button is too washed out, doesn't feel like I should be able to press it.

# Before

![before](https://i.imgur.com/pKOsLtq.png)

# After

![after](https://i.imgur.com/3bPr03Z.png)

**Comment by madvas** [comment]
I think green is not appropriate for cancel button, but can you MemeFactory's pink: 

![image](https://user-images.githubusercontent.com/3857155/55051055-31a13900-5086-11e9-8700-fe77d12da85e.png)
