### ISSUE TITLE
Show Rank N/A instead of 0

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#295]
If user submits his first meme, it shows rank #0, instead it should be showing N/A
![image](https://user-images.githubusercontent.com/3857155/55056842-e5f88a80-5099-11e9-8fc8-b94ed8ca06d8.png)

Same goes for challenger: 
![image](https://user-images.githubusercontent.com/3857155/55056915-22c48180-509a-11e9-82c0-1859fd22f2f1.png)

On MemeDetail page, challenge section, it shows up only as hashtag. Also, add space between "Address:" and 0xc23...
![image](https://user-images.githubusercontent.com/3857155/55057181-037a2400-509b-11e9-9f97-de759fa76543.png)

**Comment by jpmonettas** [comment]
I'm not being able to reproduce this. @fbielejec @benzap or @danielglauser maybe you can give it a try?

**Comment by benzap** [comment]
I see an example of it for Vote > Resolved Challenges, shows **Rank #0**

![a](https://i.imgur.com/vKYmiRr.png)

**Comment by benzap** [comment]
@jpmonettas i'll take over and see what I can do
