### ISSUE TITLE
Fix flip animation for iphone devices

### ISSUE THREAD

**Issue by benzap** [district0x/memefactory#301]
Still issues involving iphone devices when performing the flip animations as reported by @madvas,

Going to try and reproduce by grabbing safari, and other such browser to see how they fair, and possibly develop a separate implementation more closely resembling rarepepewallet (if this doesn't also pose the same issues, since the current implementation is very closely related to it already)

**Comment by madvas** [comment]
Well, we can just use some simpler animation for mobile devices. Such as fade or 2d flipping. And keep 3d flipping only for desktop.

**Comment by Bradymck** [comment]
Not sure if this is related to this or not but I can see the text from the back of the card. See image

![bug](https://user-images.githubusercontent.com/4667076/55116099-d8e49700-50ab-11e9-813d-3cfd56cc0886.PNG)
