### ISSUE TITLE
Vote buttons should stay disabled with no active account

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#315]
When user has no active account or 0 DANK, those buttons should stay disabled. They correctly do on Meme Detail Page, only Dank Registry - Vote needs fix. Actually, please make inputs disabled as well, under the same conditions. So Meme Detail page needs update too, to disable inputs. 

![image](https://user-images.githubusercontent.com/3857155/55135287-d2165c80-515d-11e9-86d9-042464d2f233.png)

**Comment by benzap** [comment]
@madvas going to lump all of the non-active account bugs together so it isn't a pull request nightmare. Will include screenshots of each case

**Comment by madvas** [comment]
Can be
