### ISSUE TITLE
Mobile: Input underline not visible

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#316]
Bottom lines underlying all inputs is not visible on mobile. Tested on real phone. In Chrome desktop mobile simulation they're visible. 

#### Safari iphone
![image](https://user-images.githubusercontent.com/3857155/55136061-f7a46580-515f-11e9-9ab2-520a079e184d.png)

#### Chrome iphone
![image](https://user-images.githubusercontent.com/3857155/55136067-fc691980-515f-11e9-85b0-a7393eb784a4.png)

**Comment by benzap** [comment]
I would try and fix this, but I can't reproduce it. From what I can tell, it looks like applying `overflow: hidden` to the input field would solve this issue
