### ISSUE TITLE
Meme ordering stopped working on QA

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#328]
As you can see all 3 sections are showing same memes in same order. Same happens when you go to Marketplace and try different sorting there. 

![ordering-bug](https://user-images.githubusercontent.com/3857155/55222077-89ce6b80-523d-11e9-99f6-14abb786a30a.png)

**Comment by jpmonettas** [comment]
@madvas no idea what is happening here in QA, I can't reproduce it locally. Looks like the graphql requests are correct and are asking for different sortings but the server is responding with auctions always in the same order

**Comment by madvas** [comment]
Would be useful if we could REPL into QA

**Comment by madvas** [comment]
Interestingly, when using input either name or tags, the ordering works correctly. 

![image](https://user-images.githubusercontent.com/3857155/55456554-84906880-5611-11e9-9497-03b6aeaeebe2.png)

**Comment by madvas** [comment]
When I put just empty space into Name input in search form, it starts working correctly

**Comment by madvas** [comment]
Unfortunately ordering still doesn't work properly. Although, now it returns different memes for different orderings, results are not correct. Newest are not newest, cheapest are not cheapest, rarest are not rarest. Only random seems to be working correctly. 

![image](https://user-images.githubusercontent.com/3857155/55528965-0ee7d380-56c9-11e9-8d1e-b836fabe21db.png)
