### ISSUE TITLE
Generators, mock data.

### ISSUE THREAD

**Issue by wambat** [district0x/memefactory#33]
I tried re-deploying with the config:
```
{:logging {:level "debug"
           :console? true}
 :generator {:memes/use-accounts 1
             :memes/items-per-account 10
             :memes/scenarios [:scenario/buy]
             :param-changes/use-accounts 1
             :param-changes/items-per-account 2
             :param-changes/scenarios [:scenario/apply-param-change]}}
```
![_001](https://user-images.githubusercontent.com/717135/45484646-1eb3c080-b755-11e8-8c5e-c53f6dbad30a.png)
![_002](https://user-images.githubusercontent.com/717135/45484647-1eb3c080-b755-11e8-8eec-4fd409215f1f.png)
![_003](https://user-images.githubusercontent.com/717135/45484648-1eb3c080-b755-11e8-9c06-b28575f9f7ab.png)
![_004](https://user-images.githubusercontent.com/717135/45484649-1f4c5700-b755-11e8-8b78-d0609ed74cbd.png)
![_005](https://user-images.githubusercontent.com/717135/45484650-1f4c5700-b755-11e8-9a77-26d91094bffc.png)
![_006](https://user-images.githubusercontent.com/717135/45484651-1f4c5700-b755-11e8-86e6-6fcb50a784b0.png)
![_007](https://user-images.githubusercontent.com/717135/45484652-1f4c5700-b755-11e8-86e2-90f9a61ffb88.png)
![_008](https://user-images.githubusercontent.com/717135/45484653-1f4c5700-b755-11e8-86c4-ada051966b4a.png)
![_009](https://user-images.githubusercontent.com/717135/45484654-1fe4ed80-b755-11e8-9d0e-dc37f4535348.png)
![_010](https://user-images.githubusercontent.com/717135/45484655-1fe4ed80-b755-11e8-971c-58efadda1827.png)
![_011](https://user-images.githubusercontent.com/717135/45484656-1fe4ed80-b755-11e8-91d3-f5deedcd7d2b.png)

**Comment by fbielejec** [comment]
fixed with changes to district-server-smart-contracts lib
