### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#34]
![image](https://user-images.githubusercontent.com/3857155/46143741-1c895000-c285-11e8-92b2-b30e6573533c.png)

* Sidebar is wider than it should be 
* Font size and color in sidebar is wrong
* "Inspired by the work of Simon..." is wrong font-size, font-weight, margins 
* "See More" is wrong color and size
* Magnifier in top bar is wrong size 
* Vertical spaces between menu items in sidebar are wrong 
* It shows 4 items in each section, but there should be 3 
* Logo should be clickable and take to home page
* "Meme Title 2" should be clickable and take to home page 

![image](https://user-images.githubusercontent.com/3857155/46143827-6114eb80-c285-11e8-907f-531e4364e5b2.png)

* Why this cannot show full number, while in designs can 
* Logo on the right shouldn't be there 

![image](https://user-images.githubusercontent.com/3857155/46144041-134cb300-c286-11e8-9d22-1e44565890fb.png)
* Weird text error

![image](https://user-images.githubusercontent.com/3857155/46144105-3ecf9d80-c286-11e8-9a5f-2ad5be26767c.png)
* "Lorem..." wrong font size and color 

![image](https://user-images.githubusercontent.com/3857155/46144249-8c4c0a80-c286-11e8-9f6e-14b8db5f017a.png)
* Shows 5 images, when I scroll to the bottom shows 6
* In designs, title is be blue color with different icon, magnifier also blue 

![image](https://user-images.githubusercontent.com/3857155/46144440-2449f400-c287-11e8-9c9c-107acec9b0bd.png)
* Cursor is too close to title 

![image](https://user-images.githubusercontent.com/3857155/46144470-375cc400-c287-11e8-8d38-499c3a2fee1a.png)
* Not styled

![image](https://user-images.githubusercontent.com/3857155/46144517-5bb8a080-c287-11e8-9a7b-70c91b1004fb.png)
* Title and icon are blue in designs
* Subtitle is wrong font-size and color 
* Buttons are wrong font-size, not looking as in designs 
* Tags don't work (probably not styling issue)
* DANK number is on the wrong size 
* Inputs have too much space in between them, vertically 

![image](https://user-images.githubusercontent.com/3857155/46144804-42fcba80-c288-11e8-9205-d4eed25aef23.png)
* Tabs have too big margin towards bottom 
* Select field not styled 
* Vote buttons are broken 
* Tags have wrong font-size and border size 

![image](https://user-images.githubusercontent.com/3857155/46145740-49d8fc80-c28b-11e8-8314-3ba569703aab.png)
This is supposed to look like this: 
![image](https://user-images.githubusercontent.com/3857155/46145750-52c9ce00-c28b-11e8-9c30-b8f60f671fc8.png)

![image](https://user-images.githubusercontent.com/3857155/46145793-6d03ac00-c28b-11e8-9bc1-e248b699a605.png)
* Wrong font-size and color 
* Missing spaces after colon 

![image](https://user-images.githubusercontent.com/3857155/46146062-0af77680-c28c-11e8-8982-fe53560f6697.png)
* Select not styled 

![image](https://user-images.githubusercontent.com/3857155/46146149-41cd8c80-c28c-11e8-8e2a-15f189138b1b.png)
* NaN shouldn't be displayed 

![image](https://user-images.githubusercontent.com/3857155/46146332-aee12200-c28c-11e8-8362-10bc32b600e8.png)
* Fonts inside yellow bar are completely off compared to design 
* Tabs have wrong vertical margins 
* "Group by memes" is not at right side as it should be  

![image](https://user-images.githubusercontent.com/3857155/46146379-d59f5880-c28c-11e8-8c33-1b2fa3a7e20d.png)
* Shadow is wrong 

![image](https://user-images.githubusercontent.com/3857155/46146574-4f374680-c28d-11e8-9701-feaaffde456b.png)
* Font spacing is very off compared to design: 
![image](https://user-images.githubusercontent.com/3857155/46146606-6413da00-c28d-11e8-8089-62a9f9c2a8fc.png)

![image](https://user-images.githubusercontent.com/3857155/46146632-7130c900-c28d-11e8-8c95-93c0cefbc194.png)
* Checkboxes are broken 

![image](https://user-images.githubusercontent.com/3857155/46146746-c5d44400-c28d-11e8-9529-bd15be5992e4.png)
* White underlying divs

![image](https://user-images.githubusercontent.com/3857155/46146987-5f035a80-c28e-11e8-9ba9-496e071dbaf5.png)
* Should have ellipsis

**Comment by jpmonettas** [comment]
Progress is being tracked in https://github.com/district0x/memefactory/blob/master/todos.org#L1
