### ISSUE TITLE
Add balances for mobile

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#344]
Since, the app is fully usable with Coinbase Wallet, it'll handy to add balances for mobile as well. 

So the idea, is to put this component: 
![image](https://user-images.githubusercontent.com/3857155/55464203-c1198f80-5624-11e9-9d94-8d1420a084a3.png)

Into the sidebar, where currently "Marketplace" menu item is. The menu items will go below balances component. 

![image](https://user-images.githubusercontent.com/3857155/55464254-e3aba880-5624-11e9-98e0-7fb042330596.png)

**Comment by benzap** [comment]
@madvas trying to work out what to do for the initial design. I'll post some previews

**Comment by benzap** [comment]
# Sketchup Example
![a](https://i.imgur.com/Gs68RtY.png)

**Comment by benzap** [comment]
@madvas let me know if this is a good start. Alternatively, we could include it in the menu

**Comment by madvas** [comment]
Please include it only in sidebar menu, like I suggested. I think that’s sufficient, doesn’t need to be visible all the time
