### ISSUE TITLE
Add Copy To Clipboard button My Memefolio for sharing URL

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#345]
We're gonna add copy to clipboard button to My Memefolio page, that will copy into clipboard full URL of user's memefolio, for sharing purposes. 

So, let's say user is at URL `http://qa.district0x.io/memefolio/` with active account `0x4c3f13898913f15f12f902d6480178484063a6fb`.  After clicking the button the url `http://qa.district0x.io/memefolio/0x4c3f13898913f15f12f902d6480178484063a6fb` will be copied into the clipboard. 

Note, we want to preserve tabs also. So, `http://qa.district0x.io/memefolio/?tab=curated` would copy as `http://qa.district0x.io/memefolio/0x4c3f13898913f15f12f902d6480178484063a6fb?tab=curated` 

Button will be displayed only on My Memefolio page, not other users' memefolios. 

Button title attribute should say "Copy shareable URL to clipboard".

[Download icon](https://github.com/district0x/memefactory/files/3039619/copy-to-clipboard.svg.zip)

![image](https://user-images.githubusercontent.com/3857155/55494579-40c74e80-5665-11e9-91aa-297d80ac96e8.png)

**Comment by jpmonettas** [comment]
@madvas what icon is that?

**Comment by madvas** [comment]
I posted the icon in issue description “Download icon”

**Comment by madvas** [comment]
or actually, use this [icon](https://github.com/district0x/memefactory/files/3041621/link.svg.zip) please
