### ISSUE TITLE
memefolio/curated regression

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#350]
Pulls but never renderes new state: http://qa.district0x.io/memefolio/?tab=curated

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/468572/55630975-45038100-57b7-11e9-8259-a3f6e99ae948.gif)

**Comment by madvas** [comment]
I was assuming this was related to broken infinite scroll

**Comment by fbielejec** [comment]
I think it's a separate issue, but can be postponed untill we resolve scrolling.

**Comment by benzap** [comment]
This is the issue I ran into when I was working on infinite scroll, I think the reagent component needs to be bumped up to a higher form

**Comment by benzap** [comment]
This might be related to #367

**Comment by fbielejec** [comment]
I can confirm this is definitely the culprit.

**Comment by fbielejec** [comment]
This issue is actually cause by: https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/memefolio/page.cljs#L707
If both voted? and challenged? buttons are unchecked the query is:
```searchMemes(curator: "0xc4e0b92df2de77c077d060e49ec63dc196980716", first: 0, after: <page-size>)```     
and every scroll event returns the same data, causing the jump behaviour.

The fix could come as a solution for #231.
The buttons could be radial (connected), or ask for ```first: 0, after: 0``` if both are unchecked.

**Comment by fbielejec** [comment]
> This might be related to #367

#367 uses :search-memes resolver, but marketplace page will definitely suffer from this.
