### ISSUE TITLE
Make Smart-contract Tests Great Again

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#363]
A while ago, many smart contracts tests were commented out, we need to get them working again. 

Please make tests working again in following files: 
https://github.com/district0x/memefactory/blob/master/test/memefactory/tests/smart_contracts/meme_tests.cljs
https://github.com/district0x/memefactory/blob/master/test/memefactory/tests/smart_contracts/registry_entry_tests.cljs
https://github.com/district0x/memefactory/blob/master/test/memefactory/tests/smart_contracts/registry_tests.cljs

**Comment by jpmonettas** [comment]
This commit fixes tests 91ca9f1
Tests passing on TravisCI (https://travis-ci.org/district0x/memefactory/builds/527336747)
