### ISSUE TITLE
Users Leaderboards infinite scroll bug

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#371]
![users-infinite-scroll2](https://user-images.githubusercontent.com/3857155/55975831-fe30f200-5cb4-11e9-92c7-9e520c49c67a.gif)

**Comment by fbielejec** [comment]
I can't reproduce ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/468572/56226666-00f46400-6074-11e9-8f15-7d387893076e.gif)

**Comment by madvas** [comment]
Still the issue for me. Possibly it's just mac related.
