### ISSUE TITLE
Implement GraphQL resolvers

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#4]
Implement resolvers at [graphql_resolvers.cljs](https://github.com/district0x/memefactory/blob/master/src/memefactory/server/graphql_resolvers.cljs). That means resolvers return data from SQL database. Syncing is already done, so all data you need should be syncing into db. Just SQL SELECT queries need to be implemented. 

For now skip implementing all "rank" fields, at the moment I'm not sure how to efficiently implement it, ideas welcome. 

Pagination in schema is inspired by [GraphQL Pagination](http://graphql.org/learn/pagination/), so try to implement according to that. 

Schema definition should be pretty self-explanatory and serve as a guide to implement this, but you still might have some questions so hit me up anytime.

**Comment by jpmonettas** [comment]
I think this can be closed now
