### ISSUE TITLE
Add My Settings page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#40]
My Settings page should look like one on NameBazaar https://namebazaar.io/my-settings. 
Should be using https://github.com/district0x/name-bazaar/blob/master/resources/public/contracts/src/District0xEmails.sol for storing emails. For mainnet we can use already deployed District0xEmails contract.

**Comment by jpmonettas** [comment]
@madvas implemented in 4f71c5c92dec79a18fed0f11c86f7a4acf1eec32
