### ISSUE TITLE
Implement emailer.cljs

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#41]
Can be implemented same way as in NB. 
We want to send email notifications after following events: 

* ChallengeCreatedEvent - Owner of meme will get email that his meme was challenged
* MemeAuctionBuyEvent - Owner will get email that his meme has been bought 
* VoteRewardClaimedEvent - Voter will get email how much reward he's obtained 
* ChallengeRewardClaimedEvent - Challenger will get email how much reward he's obtained

**Comment by jpmonettas** [comment]
@madvas what should be the subject and body for the emails?

**Comment by fbielejec** [comment]
You can get some inspiration form the NB emailer templates I guess: 

https://github.com/district0x/name-bazaar/blob/master/src/name_bazaar/server/emailer.cljs 

and

https://github.com/district0x/name-bazaar/blob/master/src/name_bazaar/server/emailer/templates.cljs

**Comment by jpmonettas** [comment]
@madvas @fbielejec where can I see/create sendgrid templates? I need to add the correct substitutions and template links if we have them.

**Comment by fbielejec** [comment]
https://sendgrid.com/templates . You probably need to create an account on sendgird and have Matus add it to the group
