### ISSUE TITLE
My Memefolio - Created shows different rank than Leaderboard - Creators

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#410]
This memefolio http://qa.district0x.io/memefolio/0x4c3f13898913f15f12f902d6480178484063a6fb?tab=created shows rank 6, but when going to Leaderboard - Creators it's on 2nd position, or when changing ordering there it's on 4th position, but never 6th. 

![image](https://user-images.githubusercontent.com/3857155/56551321-47851980-65b2-11e9-8dc3-0e556d6f032c.png)

![image](https://user-images.githubusercontent.com/3857155/56551332-4fdd5480-65b2-11e9-8917-fd58358c1909.png)

![image](https://user-images.githubusercontent.com/3857155/56551341-59ff5300-65b2-11e9-8c95-7c984b8d036a.png)

![image](https://user-images.githubusercontent.com/3857155/56551348-608dca80-65b2-11e9-9300-f76f45a8f8b7.png)

This memefolio as well http://localhost:4598/#/memefolio/0xc238fa6ccc9d226e2c49644b36914611319fc3ff?tab=created
Memefolio shows rank 8, but leaderboard says 5

**Comment by jpmonettas** [comment]
@madvas I remember we explicitly changed this tiles numbers to just being tiles position. It is not displaying any rank there. The ordering there is just search-user order by the dropdown selection.

**Comment by madvas** [comment]
hmm, in my understanding position in leaderboard equals to rank. How's creator's rank calculated then?

**Comment by jpmonettas** [comment]
@madvas this was the comment that required that https://github.com/district0x/memefactory/issues/78#issuecomment-459608701

This is creator rank calculaton https://github.com/district0x/memefactory/blob/master/src/memefactory/server/graphql_resolvers.cljs#L932-L943

**Comment by madvas** [comment]
yeah, so isn't this the same as ordering "By Created Memes" in leaderboard? Or that counts all memes,  not just whitelisted?

**Comment by madvas** [comment]
Let's do it like this: 
* In Leaderboard - Creators, we'll rename "By Created Memes" into "By Memes in Registry"
* "By Memes in Registry" will order by number of whitelisted memes in descending order, which is the same calculation like creators rank
* "By Memes in Registry" will be default sorting option in Leaderboard - Creators

**Comment by jpmonettas** [comment]
Will do that. Anyway it exists the possibility of ranks and that number to be different for some time since one is real time and the ranks are cached

**Comment by madvas** [comment]
yep, that's okay
