### ISSUE TITLE
Add Terms of Use to footer

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#424]
We need to have the attached doc displayed on Meme Factory, somewhere in the website footer, with a few requirements:

- page/button should be called "Terms of Use" (memefactory.io/terms-of-use)
- Doc should be able to be rendered/read on the website
- The doc has a section called "Acceptable Use Policy" - anywhere this appears in the body of the terms of use should self-reference link to that section
- Anywhere "Privacy Policy" appears in the body of the terms, we should link externally to the hosted Privacy policy.

You can see an example here: https://www.cryptokitties.co/terms-of-use

**Comment by Alexand0x** [comment]
[Meme Factory Terms of Use.docx](https://github.com/district0x/memefactory/files/3143388/Meme.Factory.Terms.of.Use.docx)

**Comment by madvas** [comment]
@jpmonettas Make it please normally as another page in menu. Until I get icons from Griflan, use the same styling as About page.
