### ISSUE TITLE
Add Privacy Policy to footer

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#425]
We need to have the attached doc displayed on Meme Factory, somewhere in the website footer, with a few requirements:

- page/button should be called "Privacy Policy" (memefactory.io/privacy-policy)
- Doc should be able to be rendered/read on the website
- Anywhere "Terms of use" appears in the body of the terms, we should link externally to the hosted Terms of Use.

You can see an example here: https://www.cryptokitties.co/privacy-policy

**Comment by Alexand0x** [comment]
[Meme Factory Privacy Policy.docx](https://github.com/district0x/memefactory/files/3143389/Meme.Factory.Privacy.Policy.docx)

**Comment by madvas** [comment]
@jpmonettas Make it please normally as another page in menu. Until I get icons from Griflan, use the same styling as About page.
