### ISSUE TITLE
[Mobile] Can't upload image file on Android

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#433]
Pixel 3 XL, newest version of android.

Whenever I go to the "Submit" page, and press the "Upload a file" button, I can see the button being selected, but nothing happens. No prompt to upload my file.

The rest of the submission form seems to work perfectly.

**Comment by jpmonettas** [comment]
@Alexand0x I'm not being able to reproduce this on my android phone. One thing I noticed is that first it asked me for file access permissions.
Maybe someone else with android phone can try @fbielejec ?

**Comment by jpmonettas** [comment]
Closing this now just to keep things cleaner, we can reopen if we see this again.

**Comment by Bradymck** [comment]
I'm still getting this. The Coinbase wallet has no way to get error logs either. Though same exact issue described by Alexander.

I'm on the Samsung S9. Latest os.

**Comment by Bradymck** [comment]
Small update, I can get it to work in Trust Wallet but not Coinbase Wallet.

**Comment by jpmonettas** [comment]
@Bradymck is it that you can't select the image or that you can't generate the transaction after filling everything?

**Comment by Bradymck** [comment]
I can't get the window to open to select an image. You tap the button and it does nothing.

**Comment by jpmonettas** [comment]
We did some troubleshooting with @Bradymck and figured out the problems more than android related is coinbase wallet browser related. Image selection works in chrome, will keep troubleshooting.

**Comment by jpmonettas** [comment]
I found the problem for the app not displaying on coinbase browser, that should be fixed in some next commit.
I'm still not able to upload a file since the basic input file component does nothing when clicked at least on my phone. No idea so far on how to fix this.

**Comment by fbielejec** [comment]
Create reproducible exmaple, follow up with Coinbase,

**Comment by jpmonettas** [comment]
@Alexand0x To reproduce this just create a file in a empty folder like this : 
index.html
```html
<html>
  <body>
    <input type="file" name="test" value="" />
  </body>
</html>
```

Now in a terminal inside that folder run : 
```bash
$ python -m SimpleHTTPServer 1122
```

If python installed it will expose that folder via http at port 1122

In any android phone try : 

- point chrome to http://your-local-ip:1122 and click the file chooser [WORKS]
- point coinbase wallet browser to http://your-local-ip:1122 [DOES NOT WORK]

**Comment by Alexand0x** [comment]
I reached out to the Coinbase wallet team with this report and example, but have not yet heard back. Closing this ticket for now, will reopen whenever necessary.
