### ISSUE TITLE
Transaction pop out window too far to right

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#438]
Need a little spacing between the right side of the browser window and the transaction window that pops out. When scrolling down page and the side scroll bar pops up, text on transactions such as 'pending' is cut off. 

<img width="287" alt="Screen Shot 2019-05-08 at 12 11 31 PM" src="https://user-images.githubusercontent.com/16138359/57401576-d1281000-718a-11e9-9c67-97794a9868dc.png">

**Comment by benzap** [comment]
I added a bit of spacing, here's some previews

closed
![](https://i.imgur.com/5meDQLh.png)

open
![](https://i.imgur.com/HSCUWzx.png)

**Comment by madvas** [comment]
The way I'd prefer more is to make whole section wider, not offset it. And padding between "Completed" and right border should be the same as e.g padding between "Gas used" and left border.  

![image](https://user-images.githubusercontent.com/3857155/57496641-4c5e0300-72fe-11e9-8c09-ba9e24129e6b.png)

Tx log on NameBazaar is that way

![image](https://user-images.githubusercontent.com/3857155/57496733-b8406b80-72fe-11e9-8a3f-48e3898e534e.png)
