### ISSUE TITLE
"Challenge period ends in" line runs too long

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#443]
<img width="987" alt="Screen Shot 2019-05-09 at 2 12 26 PM" src="https://user-images.githubusercontent.com/29998350/57476718-2e908f80-7265-11e9-831b-a932eb468147.png">

The challenge period ends line renders poorly, across two different lines so it reads from left to right incomprehensibly. We should try to improve this to all fit on one line, or to at least separate the timer and the text line more cleanly.

**Comment by madvas** [comment]
was already fixed by me as well https://github.com/district0x/memefactory/commit/5ab77cc9b5018eeac88563690ab4f91cf27ac9f6
