### ISSUE TITLE
Dank Registry - Browse doesn't show first meme

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#447]
As you can see, number 1 is missing, I'm pretty sure it's related to other issues with similar problem. 

![image](https://user-images.githubusercontent.com/3857155/57498916-f5f5c200-7307-11e9-8cf2-2c33f4cda3fe.png)

**Comment by benzap** [comment]
You can see if it you change to sort by issue number, likely an issue with infinite scroll or similar

**Comment by jpmonettas** [comment]
Closing this since it was fixed by f4dc9f6
