### ISSUE TITLE
Secret to reveal vote was not found in your browser 

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#452]
Voted on a challenged Meme. Waited for 24 hour challenge period to end. Instead of being able to reveal vote, getting message - "Secret to reveal vote was not found in your browser. You haven't voted". This is different from Memes that I did not vote on, which simply say - "You haven't voted." I posted an example of both below. I have not changed wallets. 

<img width="1027" alt="Screen Shot 2019-05-10 at 11 39 27 AM" src="https://user-images.githubusercontent.com/31779808/57549831-7bce3900-7319-11e9-96be-284866b3be00.png">
<img width="1029" alt="Screen Shot 2019-05-10 at 11 39 20 AM" src="https://user-images.githubusercontent.com/31779808/57549833-7bce3900-7319-11e9-8cfd-4dc42ae1a9ca.png">

**Comment by pmr212** [comment]
Issue is resolved after resync

**Comment by JayWelsh** [comment]
@pmr212 What do you mean by resync? I am experiencing this issue and I am wondering if we have the same issue.
