### ISSUE TITLE
Browser is not caching images loaded from IPFS

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#453]
Since images don't have extension, a browser thinks it's a dynamic page therefore it reloads image every time. This, in combination with infinite scroll, which remounts components every time they get in the view, causes that even the same image is loaded multiple times as you scroll up and down. Average image is around 800kB, which delivers quite unpleasant UX, waiting for images to load as you scroll up and down. Also, it puts unnecessary load on our server.

There are 2 solutions that come to my mind, not sure which one is better: 
1. We start uploading image inside folder in ipfs, so we have urls like /[ipfs-hash]/someimage.jpg. (Might be already too late for this solution)

2. We'll set in nginx config to return some cache headers for ipfs images. 
(Not sure if this will actually work, since there are some headers already)

![image](https://user-images.githubusercontent.com/3857155/57564667-b1d2f200-73d9-11e9-9b01-f1df82636469.png)

**Comment by fbielejec** [comment]
You have "disable cache"  checked in, caching is working fine.
