### ISSUE TITLE
Able to attempt to issue more cards than are available

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#457]
Able to attempt to issue more cards than are available - (i.e. issue 30 when only 25 available), which causes a tx that will never complete and goes on indefinitely. Has to be cancelled before can make any other txs. 

Suggestion: set limit for input <= cards available.

**Comment by madvas** [comment]
Can you post link to transaction please. No tx can go indefinitely.

**Comment by madvas** [comment]
According to smart-contract code https://github.com/district0x/memefactory/blob/91ca9f1da5a8683188072b12a31acf64d0bcaa5f/contracts/Meme.sol#L78 if you input larger amount, it'll mint maximum allowed amount for you. Is it what happened?

**Comment by pmr212** [comment]
I ended up cancelling the tx after a long time. Let me try a small one where amount to mint is 1 and i will try to mint 2. The network in general right now is very congested.

**Comment by pmr212** [comment]
you were correct

**Comment by madvas** [comment]
Let's disable "Issue" button when user puts larger number than allowed.

**Comment by madvas** [comment]
Fixed here https://github.com/district0x/memefactory/commit/c1c9fc7ee84340ee80a9a88a6411e2d5f389295d
