### ISSUE TITLE
Remove initial fade in animation when infinite scrolling

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#469]
Now that we fixed position shifting, the only thing missing for pleasant infinite scrolling is to get rid of this initial fade in animation. I know it's there to hide flip animation, but I hope this can be solved somehow. 

![infinite-scrll](https://user-images.githubusercontent.com/3857155/57851789-a6cdf680-780b-11e9-9794-6f765c073356.gif)

**Comment by benzap** [comment]
I think this is hiding another issue. When the query is loading, it's forcing cards to throw away the listing and reload. I'll try [removing this](https://github.com/district0x/memefactory/blob/ec6a7d73e5a8615e2beb1767c8b32129bb1ca5d8/src/memefactory/ui/dank_registry/browse_page.cljs#L67) and play around with it to if it changes anything

**Comment by benzap** [comment]
Going to need a bit more time getting this to work, but I think i've figured out why the original changes didn't work.

**Comment by fbielejec** [comment]
Closed with #535
