### ISSUE TITLE
Speeding up a vote transaction via MetaMask or clearing local storage results in secret for voting reveal being lost.

### ISSUE THREAD

**Issue by JayWelsh** [district0x/memefactory#479]
The following meme I submitted was challenged, I subsequently voted on the challenge to try and preserve my meme being added to the registry. However, I think that since I ran a "speed up" on my transaction via MetaMask, the vote secret was not saved to my browser, and now I am assuming that I will not be able to reveal my vote.

The reason why I am raising this is that the user interface did not in any way make it obvious that transactions should not be sped up, it also does not make it clear that if you clear your application data for your browser, you will lose the ability to reveal your vote. This is a pretty big issue because it can result in people voting with large portions of their holdings and then have the votes rendered entirely useless without any warning.

![Screenshot from 2019-05-18 23-55-29](https://user-images.githubusercontent.com/14224459/57975423-2b19a880-79c9-11e9-9d37-3a0dc0f169f4.png)

![Screenshot from 2019-05-18 23-54-51](https://user-images.githubusercontent.com/14224459/57975424-2ead2f80-79c9-11e9-997c-2971d7e836a9.png)

**Comment by madvas** [comment]
Into following area, under "View challenges and vote to earn more DANK" we're gonna add 2 buttons: 
"Backup vote secrets" and "Import vote secrets". First button will download json file containing vote secrets. Second one, will be to import json file into browser localstorage. You may wanna look at NB implementation of this feature. 
![image](https://user-images.githubusercontent.com/3857155/61592849-ba655700-abd8-11e9-9391-ec74af37516a.png)

Here, above "Tokens will be returned to you after revealing your vote.", we'll add another sentence: "A vote secret is stored in your browser, which needs to be used for revealing the vote later."
![image](https://user-images.githubusercontent.com/3857155/61592890-2b0c7380-abd9-11e9-9e65-51d6a7e93f42.png)
