### ISSUE TITLE
Some vote results don't add up

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#481]
There's many votes where Total Voted doesn't equal adding Voted Dank and Voted Stank. First though was that those are unrevealed votes, but that can't be the case, since we don't know amounts of unrevealed votes. 

![image](https://user-images.githubusercontent.com/3857155/57994787-0a487480-7ae9-11e9-95d9-c096db7c74b0.png)
![image](https://user-images.githubusercontent.com/3857155/57994796-12081900-7ae9-11e9-9544-a94354f897b0.png)
![image](https://user-images.githubusercontent.com/3857155/57994806-192f2700-7ae9-11e9-89e1-a3f81004dfd1.png)
![image](https://user-images.githubusercontent.com/3857155/57994822-2c41f700-7ae9-11e9-8a79-24b9e7a3979f.png)
![image](https://user-images.githubusercontent.com/3857155/57994829-35cb5f00-7ae9-11e9-8934-4311e4feb13e.png)

**Comment by fbielejec** [comment]
Probably a bad sync:
https://sentry.io/organizations/district0x/issues/1019547552/?environment=PRODUCTION&project=1306960&referrer=github_integration
