### ISSUE TITLE
No rewards, and lost collateral on the winning side of votes and challenges.

### ISSUE THREAD

**Issue by rainbowjaw** [district0x/memefactory#490]
i completed two challenges and one vote so far

https://etherscan.io/tx/0xd4440ed184faa536b31a068c47166439ed24f12d8eaff68fdfb4e9008c46e86b
https://etherscan.io/tx/0x9d9d44f5dcd7a14c37b5b4826d2cdab79721504ee37f33073a892b97ff610e54
https://etherscan.io/tx/0xe770b5ded68ab1be6e4c3b5a83f92cd5ad46e18e5cc64e0d1720fab09eab2e07

these are all of my reclaim transactions
the vote gave me 0 rewards
and the challenges gave me 50 each... but didn't return my original collateral of 100 each
so after winning two challenges and being on the winning side of a vote, I have lost 200 "dank" and gained 100 (rewards of 50 x 2)

**Comment by rainbowjaw** [comment]
https://etherscan.io/tx/0x30cb08335af5567ceefddf6552287674779a0d81cad7fd20b22323b60eb379b4

https://etherscan.io/tx/0x6954704c5c7f8aef5e4170e318c1bb8afe37285c7393e8fba979896cff039975

Still an issue, unless its because i submitted the challenge before the fix was pushed?

**Comment by madvas** [comment]
yes, fix works only on memes submitted after fix was pushed.

**Comment by madvas** [comment]
Please reach to Brady, he'll send DANK to you.
