### ISSUE TITLE
Show ENS Name instead of 0x address [enhancement]

### ISSUE THREAD

**Issue by grasponcrypto** [district0x/memefactory#494]
Instead of showing 0x address for all users, check if address resolves to an ENS name and if so, show that instead.  This would allow for more of a community feel and let users become more popular as it is easier to acknowledge and recall names than addresses.

**Comment by Alexand0x** [comment]
Rolling this into [issue 504](https://github.com/district0x/memefactory/issues/504) for better user profiles. We will likely surface and ENS names and may also create a convenient way for users to choose their names directly on the site (subdomaining, or something similar to cryptokitties).

Closing this for now.
