### ISSUE TITLE
Add embedded chat

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#497]
We're gonna add embedded chat window into MemeFactory. Part of this issue is to search around to find the most suitable service. Preferred is chat, where user's don't need to log in or register.

**Comment by fbielejec** [comment]
Firebase with anonymous login enabled?

**Comment by madvas** [comment]
That would still have to be coded, no? Or they have something out of the box? We're looking more for out-of-the-box solution.

**Comment by scottrepreneur** [comment]
In the interim, it could be beneficial to outsource that feature, allowing time for value consideration around discussion and notifications.

Though general comments could be made around memes in the registry the biggest discussion currently is likely around challenges. Having challenges cross-posted to [the] subreddit could be a good way to have discussion and activity around challenges.

I'd suggest incorporating a discord channel as an option as well, unless individual meme comments is beneficial.

**Comment by jpmonettas** [comment]
Closed by 8f86735a7e9c2b15e0b6e5671e69e64c76df2310

**Comment by madvas** [comment]
For this issue, we're gonna implement Discord Widgetbot. The type of widget, is what they call Crate: https://docs.widgetbot.io/embed/crate/

Seems like we may not even need React/reagent component for this, just add script tag. 

Widget should be configured with memefactory channel we already have in our Discord.
