### ISSUE TITLE
Add twitter bot server module

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#498]
We're gonna have twitter bot server module `memefactory.server.twitter-bot` that will tweet from MemeFactory [account](https://twitter.com/MemeFactory0x) after following events: 

1. New meme submitted
2. Meme challenged
3. Meme offered on marketplace. You need to watch out here tweet it just once, even if more cards of the same meme were offered at once. You can be checking block number in the event. All offerings of the same meme will be in the same block number. 
4. Auction has been bought. 

@Alexand0x Please provide text for each point what should be tweeted. You can provide several versions for each point, it'll will be randomly rotated, so it's not too soulless.

**Comment by Alexand0x** [comment]
ALL of the following should have the card image displayed, and should have a direct link to the meme detail page (may need to be shortened).

1. New Meme Submitted

Variation 1:
"Introducing '[MEME NAME]', The latest submission to vie for a place in the DANK registry. [LINK TO MEME DETAIL]"

Variation 2:
"The newest entry to the DANK registry, meet '[MEME NAME]'. Will it pass the bar? [LINK TO MEME DETAIL]"

2. Meme Challenged

Variation 1:
"A challenger appears... '[MEME NAME]' has had it's place in the DANK registry contested. DANK or STANK? [LINK TO MEME DETAIL]"

Variation 2:
"'[MEME NAME]' has been challenged. DANK or STANK? Vote today [LINK TO MEME DETAIL]"

3. Meme Offered on Marketplace

Variation 1:
"The exalted '[MEME NAME]' has been offered for sale. Get em while they last! [LINK TO MEME DETAIL]"

Variation 2:
"Fresh off the factory lines, '[MEME NAME]' is up the latest sell offering on Meme Factory. Grab yours today! [LINK TO MEME DETAIL]"

4. Auction has been bought

Variation 1:
"'[MEME NAME]' was just purchased for [ETH] [Dollar conversion]. Find, create, and sell more rare collectibles only on Meme Factory! [LINK TO MEME DETAIL]"

Variation 2:
"SOLD! '[MEME NAME]' auctions for a profit of [ETH] [Dollar conversion]. Buy and sell your own provably rare memes on Meme Factory."

**Comment by jpmonettas** [comment]
@Alexand0x are we going to choose one of those variations for each or we are going to use both?
@madvas do we have something already to do the dollar conversion?

**Comment by madvas** [comment]
It'll choose random variation every time. 
Nothing on server side, but you can get inspired by https://github.com/district0x/district-ui-conversion-rates

**Comment by jpmonettas** [comment]
Implemented in 4cef85cc4efc51687b4fd0471ae9bf19d639593a
