### ISSUE TITLE
Implement Dank Registry - Parameters page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#502]
So here we have designs for Dank Registry - Parameters page, which will handle voting about TCR parameters. 

[parameters-designs.zip](https://github.com/district0x/memefactory/files/3245886/parameters-designs.zip)

[parameters-icons.zip](https://github.com/district0x/memefactory/files/3245882/parameters-icons.zip)

**Comment by madvas** [comment]
https://github.com/district0x/memefactory/issues/505 needs to be done first

**Comment by jpmonettas** [comment]
This was implemented in https://github.com/district0x/memefactory/pull/560
