### ISSUE TITLE
Share to Twitter after buying a Meme

### ISSUE THREAD

**Issue by imthatcarlos** [district0x/memefactory#503]
For example, after buying a meme show the user a "Share to Twitter" button that creates a tweet with a template such as

- Meme pic
- Meme description
- @mention or link back to the NFT or market

**Comment by madvas** [comment]
Not completely the same, but we have issue for twitter bot in works: https://github.com/district0x/memefactory/issues/498

**Comment by Bradymck** [comment]
@imthatcarlos The image unfurl works now so if you share the meme URL it will show the image on all social media. We will close this now. Thanks for the suggestion!

**Comment by Bradymck** [comment]
https://memefactory.io/meme-detail/0x0856457b38475dacb32003e432cd5c3afb93e414
