### ISSUE TITLE
Style Get DANK page

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#52]
Updated icomoon icons file with menu icon
[icons (13).zip](https://github.com/district0x/memefactory/files/2692505/icons.13.zip)

![get-dank](https://user-images.githubusercontent.com/3857155/50186485-3c2b9400-031b-11e9-8e00-c1c9f6f047a1.jpg)

**Comment by madvas** [comment]
Menu item is gonna be called Get DANK, not receive dank token as in design

**Comment by jpmonettas** [comment]
@madvas https://github.com/district0x/memefactory/commit/f10f47b28879389c1795ba6963d96b016d33e3e1 styles this page. 
The remaining thing is the icon. The attached file contains a font but currently we have separate svg files for every other icon, do you have the new icon as a separate file? Or was @wambat extracting it somehow?

**Comment by madvas** [comment]
[get-dank-icon.svg.zip](https://github.com/district0x/memefactory/files/2695303/get-dank-icon.svg.zip)

**Comment by jpmonettas** [comment]
@madvas that one is black while the rest are #ff0090. I tried to edit the svg but wasn't able to make it look pretty. Also I can't use fill I think because we are loading it as icon.
