### ISSUE TITLE
bug/Rejected memes show up as accepted in registry

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#521]
### Description

When we tried to push into production last Friday, most of memes were appearing as in the registry, where in fact they were rejected from registry. We were having largest meme registry number above 400. Correct number is 205 as of now.

#### Expected behavior

Largest meme registry number should be 205

#### Actual behavior

Largest meme registry number shows 405. 

### Reproduction

I was able to reproduce with following DB file, which is synced production: 
[local.memefactory.db.zip](https://github.com/district0x/memefactory/files/3345460/local.memefactory.db.zip)

**Comment by fbielejec** [comment]
This seems to happen ONLY if the app is restarted on the same db. First sync:
```
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xbcbbd83a8babcb833594d8c206dc3ff2d1ebdc9c got number 1 assigned.", :timestamp #inst "2019-07-01T10:07:39.491-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x619d7f8b28fe734823f241390377b1d60795914e got number 2 assigned.", :timestamp #inst "2019-07-01T10:07:39.499-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x7a188c60bfcae874fc329496a892e53ba0d522b4 got number 3 assigned.", :timestamp #inst "2019-07-01T10:07:39.506-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x99b95fb3290fa50a1561d3e3e143594bd0f726e9 got number 4 assigned.", :timestamp #inst "2019-07-01T10:07:39.515-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x010358356b0072f7a1adbd2e7bff3996ae508e52 got number 5 assigned.", :timestamp #inst "2019-07-01T10:07:39.526-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x46ee7b969a5c2dbee74dcbb326b0c4709f2b5bb1 got number 6 assigned.", :timestamp #inst "2019-07-01T10:07:39.538-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x02ed32fa58129308c119001f02b5c73b785edfac got number 7 assigned.", :timestamp #inst "2019-07-01T10:07:39.547-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xf834da5b4bd281b8f05e49536603db71e38f9b7d got number 8 assigned.", :timestamp #inst "2019-07-01T10:07:39.559-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x617e8e2c747204369f53cc5a05fc28a7692f412f got number 9 assigned.", :timestamp #inst "2019-07-01T10:07:39.566-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xbb43d60598b460beea08c26f34e3eca4a4e60914 got number 10 assigned.", :timestamp #inst "2019-07-01T10:07:39.576-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x1a7eac0a90077a8782ff759c0b0fac9744a76558 got number 11 assigned.", :timestamp #inst "2019-07-01T10:07:39.583-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x951626af6ceb3471fa827d1fbfde7ac06d6995d2 got number 12 assigned.", :timestamp #inst "2019-07-01T10:07:39.590-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xad5c3542f772c780e142630d7a93f5ccaf780c2e got number 13 assigned.", :timestamp #inst "2019-07-01T10:07:39.598-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x25d8c62f0664d9291fbeee5bf1f37a18f89ef87e got number 14 assigned.", :timestamp #inst "2019-07-01T10:07:39.608-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x3a1c2658934bfa037a35e25b824ad6f5b1f1c774 got number 15 assigned.", :timestamp #inst "2019-07-01T10:07:39.615-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xbb3259134bfa74f6fcc07ddf006303351f3c5e79 got number 16 assigned.", :timestamp #inst "2019-07-01T10:07:39.622-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xcfd4697853064f7eaf2689a58167e3d7500469e3 got number 17 assigned.", :timestamp #inst "2019-07-01T10:07:39.630-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x4693b5748d540a365192ec8777a590293e07a926 got number 18 assigned.", :timestamp #inst "2019-07-01T10:07:39.638-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x5c414e9620f6aa45fef6c18304bc6d7ba88d9085 got number 19 assigned.", :timestamp #inst "2019-07-01T10:07:39.647-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xb90e7c001ed43899e1e32cc323b5590ff617e246 got number 20 assigned.", :timestamp #inst "2019-07-01T10:07:39.657-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xc99e5140c98cd0d00d17ec7e376b6b64662a309e got number 21 assigned.", :timestamp #inst "2019-07-01T10:07:39.667-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xac7ff4b5814750e585b7186dc6363ae712f101fd got number 22 assigned.", :timestamp #inst "2019-07-01T10:07:39.675-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xb2cc9be4d2d44af16f23ec8ce06e347e2a56e983 got number 23 assigned.", :timestamp #inst "2019-07-01T10:07:39.682-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x0077c5ac9c22bc86cb5bd65690299f8c20447c02 got number 24 assigned.", :timestamp #inst "2019-07-01T10:07:39.691-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xe9cf5556e06a30f2b38d62bdf9b6d48a1ea905d0 got number 25 assigned.", :timestamp #inst "2019-07-01T10:07:39.703-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xa2275c76bd9ed5eee9d38ca433edba434180c06e got number 26 assigned.", :timestamp #inst "2019-07-01T10:07:39.714-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xc6ac94b3617e96db4b4b265026d099f61ba496c7 got number 27 assigned.", :timestamp #inst "2019-07-01T10:07:39.723-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x240b93e1a27616bce8f3cfd28fd4f8fef3b54813 got number 28 assigned.", :timestamp #inst "2019-07-01T10:07:39.739-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x47be53454c641af4e6c9812e795158d9a4576da9 got number 29 assigned.", :timestamp #inst "2019-07-01T10:07:39.747-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x35ed59ac1d95c023088fe07cb6865681292d7c6f got number 30 assigned.", :timestamp #inst "2019-07-01T10:07:39.754-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xc41831ba6ffcf2243fe365a2bf452c7effbd02ef got number 31 assigned.", :timestamp #inst "2019-07-01T10:07:39.763-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x835d5b62e945e585fdffe25dcea99eceb96e74e6 got number 32 assigned.", :timestamp #inst "2019-07-01T10:07:39.771-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xb9cd22f125b0e1c1f6606e7e8f2cd95f1111969b got number 33 assigned.", :timestamp #inst "2019-07-01T10:07:39.779-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xb9384035627463298f270173513e68f97d44782c got number 34 assigned.", :timestamp #inst "2019-07-01T10:07:39.787-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x237531dd696643d3d89accb360ca934df65b6e18 got number 35 assigned.", :timestamp #inst "2019-07-01T10:07:39.800-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xd1ff631a586bd2dc3fbc79969d69249396004567 got number 36 assigned.", :timestamp #inst "2019-07-01T10:07:39.810-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x071c3e2d4c9298965269385d5107662c5bbf0b66 got number 37 assigned.", :timestamp #inst "2019-07-01T10:07:39.822-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x5380088501b6296638a40f003c19caf4c28ea8ad got number 38 assigned.", :timestamp #inst "2019-07-01T10:07:39.830-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x7936ce20226dacef4d578a73b2858c6e784aeabd got number 39 assigned.", :timestamp #inst "2019-07-01T10:07:39.839-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x50b6ee8b1ce62b51bf70de6faec9d0310c8c0878 got number 40 assigned.", :timestamp #inst "2019-07-01T10:07:39.846-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xecacac06c5db5ce381a680cedbc51d96796c0973 got number 41 assigned.", :timestamp #inst "2019-07-01T10:07:39.854-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x5a8e37a6f2a2565a48d8a74efd25b94820dc29bc got number 42 assigned.", :timestamp #inst "2019-07-01T10:07:39.865-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x2024bef9f45ade8b3494392b1586e3fc07bdb555 got number 43 assigned.", :timestamp #inst "2019-07-01T10:07:39.875-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xf7b7092ef9a420a1efbdae14cd455d3521d6c9a3 got number 44 assigned.", :timestamp #inst "2019-07-01T10:07:39.885-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x7ca55ee57bed8f772fa8dfd3bd5998a57c2c7c26 got number 45 assigned.", :timestamp #inst "2019-07-01T10:07:39.895-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xf5ed60305ee317ccdb3bca87500a121052a35896 got number 46 assigned.", :timestamp #inst "2019-07-01T10:07:39.906-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x1073a6dace070debf26d4b06803a7bcce4430260 got number 47 assigned.", :timestamp #inst "2019-07-01T10:07:39.915-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x457fc82590ccc666d67c9e843a749219c631fb80 got number 48 assigned.", :timestamp #inst "2019-07-01T10:07:39.923-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xa82e5ef94c61de9a1a4401b132f40c669ae98474 got number 49 assigned.", :timestamp #inst "2019-07-01T10:07:39.930-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x1df469f522ae250777975d1fac044b0d24d68bbb got number 50 assigned.", :timestamp #inst "2019-07-01T10:07:39.939-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xa98887c5f9d449dce3121003d6a62af7f1fef463 got number 51 assigned.", :timestamp #inst "2019-07-01T10:07:39.950-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xf01bacbb45a9c6323282f4561ed750bf6d048a56 got number 52 assigned.", :timestamp #inst "2019-07-01T10:07:39.960-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x334dd0c44d401de6ee7823c015922386baad3926 got number 53 assigned.", :timestamp #inst "2019-07-01T10:07:39.971-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x68bdb99ae132e23a5a954d8b3250aae2196e2075 got number 54 assigned.", :timestamp #inst "2019-07-01T10:07:39.982-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0x691fe76d7f8881935d66b0147d0c79f42c451848 got number 55 assigned.", :timestamp #inst "2019-07-01T10:07:39.990-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xe3fb9e4e4f933348d89ba584ed055d31aff89bd0 got number 56 assigned.", :timestamp #inst "2019-07-01T10:07:39.999-00:00"}
{:level :info, :?ns-str "memefactory.server.syncer", :?file "*cider-repl district0x/memefactory:localhost:46579(clj)*", :?line 45, :message "Meme 0xda4d34e28414a55052f5ac6118d62fc29fe0c20d got number 57 assigned.", :timestamp #inst "2019-07-01T10:07:40.011-00:00"}```

If I now shut down the app:

```
INFO Meme 0xbcbbd83a8babcb833594d8c206dc3ff2d1ebdc9c got number 201 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x619d7f8b28fe734823f241390377b1d60795914e got number 202 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x7a188c60bfcae874fc329496a892e53ba0d522b4 got number 203 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x99b95fb3290fa50a1561d3e3e143594bd0f726e9 got number 204 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x010358356b0072f7a1adbd2e7bff3996ae508e52 got number 205 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x46ee7b969a5c2dbee74dcbb326b0c4709f2b5bb1 got number 206 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x02ed32fa58129308c119001f02b5c73b785edfac got number 207 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xf834da5b4bd281b8f05e49536603db71e38f9b7d got number 208 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x617e8e2c747204369f53cc5a05fc28a7692f412f got number 209 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xbb43d60598b460beea08c26f34e3eca4a4e60914 got number 210 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x1a7eac0a90077a8782ff759c0b0fac9744a76558 got number 211 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x951626af6ceb3471fa827d1fbfde7ac06d6995d2 got number 212 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xad5c3542f772c780e142630d7a93f5ccaf780c2e got number 213 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x25d8c62f0664d9291fbeee5bf1f37a18f89ef87e got number 214 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x3a1c2658934bfa037a35e25b824ad6f5b1f1c774 got number 215 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xbb3259134bfa74f6fcc07ddf006303351f3c5e79 got number 216 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xcfd4697853064f7eaf2689a58167e3d7500469e3 got number 217 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x4693b5748d540a365192ec8777a590293e07a926 got number 218 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x5c414e9620f6aa45fef6c18304bc6d7ba88d9085 got number 219 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xb90e7c001ed43899e1e32cc323b5590ff617e246 got number 220 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xc99e5140c98cd0d00d17ec7e376b6b64662a309e got number 221 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xac7ff4b5814750e585b7186dc6363ae712f101fd got number 222 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xb2cc9be4d2d44af16f23ec8ce06e347e2a56e983 got number 223 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x0077c5ac9c22bc86cb5bd65690299f8c20447c02 got number 224 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xe9cf5556e06a30f2b38d62bdf9b6d48a1ea905d0 got number 225 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xa2275c76bd9ed5eee9d38ca433edba434180c06e got number 226 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xc6ac94b3617e96db4b4b265026d099f61ba496c7 got number 227 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x240b93e1a27616bce8f3cfd28fd4f8fef3b54813 got number 228 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x47be53454c641af4e6c9812e795158d9a4576da9 got number 229 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x35ed59ac1d95c023088fe07cb6865681292d7c6f got number 230 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xc41831ba6ffcf2243fe365a2bf452c7effbd02ef got number 231 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0x835d5b62e945e585fdffe25dcea99eceb96e74e6 got number 232 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
INFO Meme 0xb9cd22f125b0e1c1f6606e7e8f2cd95f1111969b got number 233 assigned. in memefactory.server.syncer[*cider-repl district0x/memefactory:localhost:46579(clj)*:45] at Mon Jul 01 2019 15:08:07 GMT+0200 (Central European Summer Time)
...
```

**Comment by madvas** [comment]
Most likely related to code here https://github.com/district0x/memefactory/blob/c11c121c8a1ca9309fd618f6d68e3541c93c6e2a/src/memefactory/server/syncer.cljs#L416-L419
