### ISSUE TITLE
Curators scoreboard challenge counter does not match actual history [BUG]

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#527]
### Description
*Type*: Bug

*Summary*: This is much easier to explain with pictures. It's a very odd bug I discovered when totaling data for a recent blog post.

To start, visit https://memefactory.io/leaderboard/curators and then sort using any option. Next, add all of the challenges that have succeeded (go through each tile and add the numbers circled below)
![image](https://user-images.githubusercontent.com/29998350/60737053-4ca60380-9f27-11e9-8517-7a5bf745c5df.png)

Once you do this for all participating addresses, you'll have a number that should represent the total number of challenge that have "succeeded", meaning they had a "STANK" vote result.

Now, we go to the resolved votes page https://memefactory.io/dankregistry/vote?tab=Resolved%20Challenges

Simply scroll through and add up every single vote that has had a "STANK" result. This should be equal to our first number, but isn't.

#### Expected behavior
Using other sources of data from the registry and meme submissions, we can deduce that the complete history is in fact shown on https://memefactory.io/dankregistry/vote?tab=Resolved%20Challenges. The expected behavior is that the curators scoreboard would correctly account for this in challenge numbers.

#### Actual behavior

The numbers displayed in challenge counters on the curator's scoreboard are not reflective of the total history of challenges.

**Comment by jpmonettas** [comment]
After https://github.com/district0x/memefactory/pull/543 gets merged, this can be used to test it in any environment
```clojure
(in-ns 'memefactory.server.graphql-resolvers)
(require '[district.server.graphql :as g])


;; Both values should be equal
(=

 ;; Count all the blacklisteds in voting page
 (let [now (utils/now-in-seconds)]
   (->> (search-memes-query-resolver nil {:statuses
                                          ["regEntry_status_blacklisted" "regEntry_status_whitelisted"],
                                          :order-by "memes_orderBy_revealPeriodEnd",
                                          :order-dir "desc", 
                                          :challenged true})
        :items
        (filter #(= (reg-entry-status now %) :reg-entry.status/blacklisted))
        count))

 ;; Sum all the users challenges success
 (->> (g/run-query 
       {:queries   [[:search-users
                     {:order-by :users.order-by/total-collected-memes
                      :order-dir :desc
                      :first 10000
                      :after "0"}
                     [:total-count
                      :end-cursor
                      :has-next-page
                      [:items [:user/total-created-challenges-success]]]]]} )
      :data :search-users :items
      (map :user/total-created-challenges-success)
      (reduce + 0)))
```
