### ISSUE TITLE
Marketplace filter radio buttons collide with tag form/[BUG]

### ISSUE THREAD

**Issue by Alexand0x** [district0x/memefactory#542]
https://memefactory.qa.district0x.io/marketplace

See screenshot below. The tag entry form overlays the radio buttons for sorting.

![image](https://user-images.githubusercontent.com/29998350/61067497-aa2dca80-a3d5-11e9-8300-a43776242ec2.png)

**Comment by fbielejec** [comment]
Can't reproduce 
![2019-07-15-1563175254_screenshot_1920x1080](https://user-images.githubusercontent.com/468572/61200517-fb91ce80-a6e1-11e9-9e5c-1ad0a0cb70da.jpg)

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/61200692-838cce00-a70c-11e9-82c5-fc9b0fb1736b.png)
can't reproduce, Chrome on Mac
