### ISSUE TITLE
Load DankFaucet with ETH and DANK when deploying

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#56]
Script deploying contracts should add some DANK and ETH to the deployed DankFaucet.
To fund it with DANK see previous code where transfers are done to the last account. 

To fund it with ETH use the payable function from the contract, i.e.:

    dankFaucet.sendEth (Object.assign(opts, {gas: 200000, value: web3.toWei(0.1, "ether")}));

Add print statements that show ETH and DANK balance after transactions to confirm everything went fine:

```
     .then (([dankFaucet,
              dankToken]) => {
                return Promise.all ([dankFaucet.getBalance (),
                                                dankToken.balanceOf (dankFaucet.address)]);
              })
     .then (([ethBalance,
              dankBalance]) => {
                console.log ("@@@ ETH balance of DankFaucet", ethBalance);
                console.log ("@@@ DANK balance of DankFaucet:", dankBalance);
              });
```

You need to decide on the actual amount of DANK and ETH the contract should get, depending on how the oracle charges.

**Comment by danielglauser** [comment]
Fixed with this PR: https://github.com/district0x/memefactory/pull/58
