### ISSUE TITLE
votes do not count towards final pass/fail

### ISSUE THREAD

**Issue by mathos83** [district0x/memefactory#565]
### User Story

As a user, I want to vote so that memes either pass/fail.

### Description

Bug

I voted for a meme, did reveal my vote, got reward, but the final result of pass/fail (dank/stank) did not take my votes into account.

#### Expected behavior

I expect my votes to count towards final decision about pass/fail

#### Actual behavior

votes are not counted towards pass/fail

### Reproduction

voted for another meme, revealed my vote, result not counted towards final decision about pass/fail

- Open webapp, got to a challenged meme, click into vote field, enter desired amount of dank, click on vote, wait for the voting period to conclude, after reveal period started reveal votes. Claim reward. Check under the meme which shows total voted amount of dank correctly but my vote doesn't show under either dank or stank, but it shows under total voted

### Solution

N/A

### Additional Information

Let's take this meme (as one of the 3 I discovered so far) as an example: https://memefactory.io/meme-detail/0x7b61835e7d8fb12577376927afa7bd26d5fc604e

under the voting I can see this info which is incorrect: 

Voted Dank: 8.1% (50,000)
Voted Stank: 32.5% (200,000)
Total voted: 615,000
You voted: 365,000 for DANK (730%)

You can clearly see that I voted (voted dank for this one) but dank only shows 50k of someone else.

We can check on etherscan: https://etherscan.io/address/0x7b61835e7d8fb12577376927afa7bd26d5fc604e#tokentxns

There you can clearly see my address voting 365.000 dank, it comes in it comes out and also my address receiving reward which is a proof that I revealed my votes. We can also see the only other 50k dank vote for dank, the rest is voting for stank. So clearly my votes did not count which is a bug.

I have discovered 3 memes in total with this issue. I don't know if there are more I did not check everything obviously. I'm reporting the meme above as an example which is not my own creation, and 2 more that are of my creation:

1) This one is the same story - only my votes didn't count:
https://memefactory.io/meme-detail/0x67427252dda9ced5e83cacbc2654e27eb89e64d3

etherscan: https://etherscan.io/address/0x67427252dda9ced5e83cacbc2654e27eb89e64d3#tokentxns

2) https://memefactory.io/meme-detail/0x60a7bf13925aa75cf3d031e1dfcf7a0ce09ff6e9
this is an older one that got accepted while ago (you can see it was purchased 3x already) but then at some point it got the status "stank". My votes on this one were counted, but votes of someone else did not. No idea how this happened, I did not search for etherscan tx address of this one since it is obviously a bug (was purchased by collectors)

**Comment by Bradymck** [comment]
This is clearly an issue with votes not being counted properly. If it's an unrevealed vote issue this should be clearly shown in the UI so we know if it's an unrevealed vote issue or some other problem.

**Comment by fbielejec** [comment]
closed with #572
