### ISSUE TITLE
bug/ unable to list meme for sale as duration field error (Testnet)

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#591]
[comment]: # Unable to list meme for sale *On Testnet*
<img width="659" alt="Screen Shot 2019-08-13 at 10 28 21 AM" src="https://user-images.githubusercontent.com/31779808/62963649-43297a00-bdb6-11e9-9c4d-bfe14a1d6975.png">

### User Story

As a user, I want to list a meme so that it can be in the marketplace.

### Description

[comment]: # 
*Type*: Bug

#### Expected behavior

[comment]: # I expected to be able to fill in some value for duration when listing the meme

#### Actual behavior

[comment]: # The duration note says value should be between 1 and 0. Values 1, 0, and 0.5 do not work. 

### Reproduction

[comment]: # see above

### Solution

[comment]: # 
- [1] Allow for any or at least some value to be entered for duration. 

### Additional Information
n/a

**Comment by jpmonettas** [comment]
I wasn't able to reproduce. This was probably related to a bug introduced when redesigning parameters which is fixed now.
I will close it but reopen if we see it again.

**Comment by madvas** [comment]
https://sentry.io/organizations/district0x/issues/1135458727/events/dd03bb9b7d0d4fc6ab0b55952de2ab8f/?environment=QA&project=1306960&statsPeriod=14d
