### ISSUE TITLE
[QA] [BUG] Some Gif images giving an error even within size limit

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#604]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

When submitting memes, some Gif images don't trigger a MetMask transaction popup

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarize the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Some Gif images will work and others do not. The test was done with several Gif images.

#### Expected behavior

[comment]: # (Describe what you expected to happen.)

#### You add, title, tag and comment, then submit. The entry clears out and nothing happens. See below for Dev console errors.

[comment]: # (Describe what actually happened.)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- You can reproduce this issue by submitting the following images (Both within file size limit):

This one is already in the mainnet registry (Does not work on QA)
![QmRQf6XcEx12GNoHu3cDvYbEkdgra4peZDGcZodqKXme2r](https://user-images.githubusercontent.com/4667076/63290283-6359ad00-c27e-11e9-86d5-d3aefc012a18.gif)
This one is not (Works on QA)
![tenor](https://user-images.githubusercontent.com/4667076/63290320-740a2300-c27e-11e9-8caa-c2ba328717bb.gif)

### Solution

[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:

- [ ] It's unclear what is causing this.

### Additional Information

[comment]: # (Please do your best to fill this out.)
- browser console logs: 
![Capture](https://user-images.githubusercontent.com/4667076/63290940-c13ac480-c27f-11e9-8821-21497bbde2ab.PNG)

[comment]: # (browser version)
- Browser: Chrome

**Comment by fbielejec** [comment]
fixed with ipfs dockerized nginx config
