### ISSUE TITLE
[QA] [FEATURE] Change 'Duration' parameter to hours instead of seconds

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#605]
# Problem

Anything under an hour is too fast for people to respond to any challenge, reveal, or vote. Also memes and proposals can instantly be accepted if set to one second. This is also a poor user experience when trying to calculate days in seconds.  If people were not paying attention at a slow period and this proposal for 1 second challenge period passed, people could fill the registry with memes instantly if we don't do this. 
 
## Implementation

This should include a required minimum that is reasonable for people to respond and vote.
It should be discussed what a reasonable minimum and maximum should be. Anything outside this range should not allow a proposal to be submitted. 

## Notes

Mainly just need to ensure this is never retroactive for past proposals and meme entries so people can't force a meme or proposal into the registry, or front run people before they can reveal their votes. Challenges are not retroactive and you can't front run and force a currently active proposal. However this was only tested for challenging but not other scenarios where the same front running could occur.
## Future Steps

We just need to test the UX and make sure it works well and you can't set it ridiculously low.

**Comment by Alexand0x** [comment]
The parameters are coded in at the smart contract level in seconds. We could convert them into hours in the interface display on the parameters page, but ultimately the contract will accept valid numbers on the order of a few seconds.

Creating arbitrary limits to these parameters defeats the purpose of letting people vote on them anyway. If someone makes a bad parameter change proposal, we should challenge and downvote it.

**Comment by Alexand0x** [comment]
If we want to fix this in the interface, please edit and reopen the ticket
