### ISSUE TITLE
Styling Issues 2

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#61]
![image](https://user-images.githubusercontent.com/3857155/51366228-0692ea00-1b17-11e9-9118-cba541ac6288.png)
* On Dank Registry - Vote page it correctly shows "Voted" when already voted, but on meme detail page buttons should as well show "Voted"
* "You can vote with up to 9.99873997e+26 DANK" This number is probably in wei
* Padding of white panel should be same from the top and bottom. Make bottom padding same as top one currently is. Also, padding from left should be same as currently padding from right is. 
* Make border color between columns `rgba(174, 175, 177, 0.5)`
---

![image](https://user-images.githubusercontent.com/3857155/51366979-22988a80-1b1b-11e9-97b8-64219f871e81.png)
* Make space between lines consistent. Should look like: 
![image](https://user-images.githubusercontent.com/3857155/51366996-30e6a680-1b1b-11e9-840e-29892c19e705.png)

---
![image](https://user-images.githubusercontent.com/3857155/51367139-c5510900-1b1b-11e9-999d-558e26fa38ff.png)
* Add more space between text and time. Should look like: 
![image](https://user-images.githubusercontent.com/3857155/51367505-8754e480-1b1d-11e9-83df-7f9be4848634.png)
---
![image](https://user-images.githubusercontent.com/3857155/51367541-aeabb180-1b1d-11e9-8209-141db5cca9c1.png)
* Add more space between inputs and buttons. Should look like: 
![image](https://user-images.githubusercontent.com/3857155/51367527-99cf1e00-1b1d-11e9-9da6-c25fdb50403a.png)

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51367780-bcae0200-1b1e-11e9-89da-937d21f695b2.png)
* How is this working? How can it know email address when it's encrypted?

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51368039-0c40fd80-1b20-11e9-92a1-aa8f34064fc7.png)
* Disable Create Offering when there's error in the form
* Make Create Offering button `width: 55%`

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51368361-a8b7cf80-1b21-11e9-9f80-4ee3a433218c.png)
* After already successfully one time submitting Create Offering, tried to submit again, but tx is failing. Should be able to submit multiple times as long as user still owns some cards. When owning 0, Create Offering button should change to disabled.

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51368489-35628d80-1b22-11e9-80ab-5272c0658f46.png)
* 3/10 should be on separate line. Marketplace page 
In designs looks like, make it look the same please 
![image](https://user-images.githubusercontent.com/3857155/51368503-4b704e00-1b22-11e9-8bc2-80567ae63dac.png)

**Comment by madvas** [comment]
Forgot to fix this https://github.com/district0x/memefactory/issues/45#issuecomment-454808653

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51368748-4233b100-1b23-11e9-926f-d8ac6c5a1691.png)
* Missing space

**Comment by madvas** [comment]
After buying meme, notification currently says "Auction [meme-title] is now yours". It should say "You successfully bought [meme-title]"

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51368867-c7b76100-1b23-11e9-96a1-35a568e61194.png)
* All pages are somehow missing padding from the bottom, cannot really scroll down do see white panel ending

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369207-2204f180-1b25-11e9-9d5b-8ffea86336a0.png)
* When there's nothing in history, it should show 1 line under the table header saying "This meme hasn't been traded yet."

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369306-9dff3980-1b25-11e9-8d5c-d668ae8b419f.png)
* Leaderboard pages broken

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369704-28946880-1b27-11e9-9f91-8b1a2ce632da.png)
* Leaderboard tiles on mobile can be bigger and have less space between them

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369759-52e62600-1b27-11e9-9dee-2375830c0ba3.png)
* Make background color of tags transparent

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369854-a5bfdd80-1b27-11e9-8833-ec0ff9d6728b.png)
![image](https://user-images.githubusercontent.com/3857155/51369866-ace6eb80-1b27-11e9-80fc-d357cf20286e.png)
* For tablets cards should be aligned to the centre of row

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51369944-f7686800-1b27-11e9-891a-3de485c15bb8.png)
* Broken for ipad (all leaderboard pages), can be aligning same way as for mobile

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51370049-4adab600-1b28-11e9-94d2-6a11bc493c24.png)
* Broken for ipad portrait view. Doesn't show details and right side is cut off. Can be aligning same way as for mobile.

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51370186-cf2d3900-1b28-11e9-8a3e-de7cc954e517.png)
* Missing icon. Memefolio - Curated, Voted Dank

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51370223-eff58e80-1b28-11e9-9d3d-855f1df52c8f.png)
* Change to "Vote Unrevealed"

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51370247-0ac80300-1b29-11e9-8f72-97462b946baa.png)
* Shows DANK in wei 
* "You voted" doesn't show the number
* When already collected, button should say "Collected"

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/51370475-d739a880-1b29-11e9-89e1-2d83137beac0.png)
* Make Seller and Buyer address clickable. For Seller it should take to user's Memefolio - Sold. 
For Buyer it should take to user's Memefolio - Collected.

**Comment by jpmonettas** [comment]
> ![image](https://user-images.githubusercontent.com/3857155/51367780-bcae0200-1b1e-11e9-89da-937d21f695b2.png)
> 
> * How is this working? How can it know email address when it's encrypted?

@madvas we are storing setting in localstorage also

**Comment by jpmonettas** [comment]
> Forgot to fix this [#45 (comment)](https://github.com/district0x/memefactory/issues/45#issuecomment-454808653)

Weird, it is working for me 
![latest-screenshot](https://user-images.githubusercontent.com/786299/51497801-0d359180-1da3-11e9-90e1-196d53d5f111.png)
