### ISSUE TITLE
feature/Remove vote quorum from Meme Factory

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#636]
We're not going to use vote quorum, both in smart-contracts and clojuerscript. 

This will require redeploying Meme.sol, ParamChange.sol, MemeFactory.sol, ParamChangeFactory.sol. 

+ All the occurences of quorum in UI and server side.

**Comment by jpmonettas** [comment]
We are abandoning this since we decided to remove the vote quorum parameter since there were hard to implement solutions. All the work has been done in fix/quorum-issue-544
