### ISSUE TITLE
feature/Filtering based on NSFW tag

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#639]
Not Safe For Work images should be tagged with NSFW tag. Then NSFW checkboxes will be added to following pages: Marketplace, Dank Registry - Browse, Leaderboard - Dankest Memes, Memefolio, Related Memes.

NSFW checkbox is unchecked by default.

Home Page will not have NSFW checkbox and will not display images with NSFW tag.

**Comment by jpmonettas** [comment]
![dank-registry](https://user-images.githubusercontent.com/786299/65532275-ed2a1500-ded1-11e9-89a5-ef97f94413ed.png)
![detail](https://user-images.githubusercontent.com/786299/65532276-ed2a1500-ded1-11e9-935a-0fd42a3e2732.png)
![leader](https://user-images.githubusercontent.com/786299/65532277-ed2a1500-ded1-11e9-8773-b2e2999a2c9e.png)
![market](https://user-images.githubusercontent.com/786299/65532278-edc2ab80-ded1-11e9-8084-9853806767a2.png)
![memefolio](https://user-images.githubusercontent.com/786299/65532279-edc2ab80-ded1-11e9-92b0-ffd3d6fcbf0a.png)

**Comment by madvas** [comment]
checkbox styling should be same as other ones

![image](https://user-images.githubusercontent.com/3857155/65691224-adfaf000-e09a-11e9-9f01-b8730c734441.png)

**Comment by jpmonettas** [comment]
In latest commits they look like this :
![updated-check-leader](https://user-images.githubusercontent.com/786299/65692425-e4a81a80-e048-11e9-90e7-ca176c5b4436.png)
![updated-check-market](https://user-images.githubusercontent.com/786299/65692426-e4a81a80-e048-11e9-80dc-2271f30c9759.png)

**Comment by madvas** [comment]
On Marketplace page it should go under radio box

**Comment by jpmonettas** [comment]
![updated-check-market](https://user-images.githubusercontent.com/786299/65714868-56e12500-e072-11e9-9b33-056028876f18.png)
