### ISSUE TITLE
Raise the size of submissions from 1.5MB to at least 3MB/[FEATURE]

### ISSUE THREAD

**Issue by davidullo** [district0x/memefactory#641]
# Problem

I think the actual limit of 1.5MB is fine for static pictures in PNG or JPG format, but it's terrible for GIFs cause it's too stringent, and we always need to make some compromise to get an animated meme into the registry. Honestly, I think that 3MB is still a stringent limit, but would give artists much more freedom in the creation process

## Implementation

Raising the limit would be a good way to solve this, but I'm not sure if there are other ways to get the same result in a more efficient way

**Comment by fbielejec** [comment]
MF supports mp4 format, closing
