### ISSUE TITLE
QA bug/Memes disappearing after submission. Not found in any tab. 

### ISSUE THREAD

**Issue by pmr212** [district0x/memefactory#665]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to submit a meme so that it can be accepted into the registry.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarize the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I submitted 2 memes. First with a "NSFW" tag. And second with a generic "cat" tag. I expected the memes to then go to the challenge tab after their respective transactions were successful. However both memes disappeared with no trace after their transactions were both successful. 

#### Expected behavior

[comment]: # (Describe what you expected to happen.)
Expected memes to appear in challenge tab. 

#### Actual behavior

[comment]: # (Describe what actually happened.)
Memes disappeared. 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open webapp
- Select a properly formatted meme (file size, proportions)
- Fill out information about meme
- Submit Meme
- Wait for transaction to clear
- Observe the meme is nowhere to be found

### Solution

[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:

-  The meme needs to appear in the challenge tab. 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- browser console logs: ...
[comment]: # (browser version)
- Browser: Chrome

#### Logs

[comment]: # (if any sentry logs connected please paste links here)

Meme tx 1: https://ropsten.etherscan.io/tx/0x255f84802c30337754122c0fa1d9ec6f267fc39a41ff1ca5e5886199fa551923

Meme tx 2: https://ropsten.etherscan.io/tx/0x4716b2e8868af0c20ef0ae65df7d2d200f2d2a9ede4166fecc14899e3eb291b6

**Comment by jpmonettas** [comment]
Both memes are showing after restarting QA memefactory server.

Before restarting it was in a loop with this logs:
```
ERROR ping
{:error #object[Error Error: connection not open]}
 in district.server.web3[/tmp/form-init9009599664426207308.clj:38] at Tue Dec 17 2019 18:26:46 GMT+0000 (Coordinated Universal Time)
connection not open on send()
ERROR ping
{:error #object[Error Error: connection not open]}
 in district.server.web3[/tmp/form-init9009599664426207308.clj:38] at Tue Dec 17 2019 18:26:47 GMT+0000 (Coordinated Universal Time)
connection not open on send()
ERROR ping
{:error #object[Error Error: connection not open]}
 in district.server.web3[/tmp/form-init9009599664426207308.clj:38] at Tue Dec 17 2019 18:26:48 GMT+0000 (Coordinated Universal Time)
connection not open on send()
ERROR ping
{:error #object[Error Error: connection not open]}
 in district.server.web3[/tmp/form-init9009599664426207308.clj:38] at Tue Dec 17 2019 18:26:49 GMT+0000 (Coordinated Universal Time)
connection not open on send()

```

so syncer wasn't processing new events.

@fbielejec any ideas what can cause that?

**Comment by fbielejec** [comment]
Logged error seems to be coming from the keep-alive: https://github.com/district0x/district-server-web3/blob/master/src/district/server/web3.cljs#L31

However an error should have the same affect as a ws disconnect event : https://github.com/district0x/district-server-web3/blob/master/src/district/server/web3.cljs#L67

It should create a new websocket connection :thinking:
