### ISSUE TITLE
Meme Deck

### ISSUE THREAD

**Issue by MouyouMoos** [district0x/memefactory#672]
# Problem

I can't see what other people are buying or liking. 

## Implementation

create a profile / meme deck where other people see what i buy / like

## Notes

i think with meme decks people challenge each other who has the nicest deck and the rarest / hypest memes

and the you can have a deck ranking

**Comment by Alexand0x** [comment]
It's unclear what's being requested here that goes beyond the current Memefolio, but rolling this into https://github.com/district0x/memefactory/issues/504
