### ISSUE TITLE
hype score

### ISSUE THREAD

**Issue by MouyouMoos** [district0x/memefactory#675]
# Problem

i can't see the popularity of a meme. 

## Implementation

Create a meme hype score based on the popularity of the meme and the popularity of the meme creator. each like pushes popularity. the higher the popularity of the person who likes stuff the higher the impact of his / her like. also the more you sell , the more it get shared, the more it get traded. lots of stuff wich influence the hype score

**Comment by Alexand0x** [comment]
We already have popularity measures - they're based on marketplace metrics rather than something more arbitrary and free to generate like views or likes.

https://memefactory.io/leaderboard/dankest
