### ISSUE TITLE
challenge meme rejection

### ISSUE THREAD

**Issue by MouyouMoos** [district0x/memefactory#676]
# Problem

i can't see all the rejected meme and can't challenge the rejection if i missed the voting

## Implementation

put 500 DANK in to open the case again

**Comment by Alexand0x** [comment]
You can see resolved challenges here: https://memefactory.io/dankregistry/vote?tab=Resolved%20Challenges

If a meme is rejected and you disagree with the decision, the meme creator can always resubmit the meme with whatever change necessary to succeed in the registry the second time around.
