### ISSUE TITLE
Create Sendgrid Email Template

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#75]
So here's email [template](https://github.com/district0x/memefactory/files/2810622/MemeFactoryEmailTemplate.zip). 

Log in into our Sendgrid (will send you credentials on Slack), go to Templates -> Legacy. You'll find there NameBazaar template, which is pretty much same as for MF, but different colors, logo, etc. So copy that one and edit, so it looks like MF template. Then use new template ID in MF code. 

![meme-factory_email-template](https://user-images.githubusercontent.com/3857155/51954101-80a96400-2471-11e9-8641-5e2a2ab6ae54.jpg)

**Comment by fbielejec** [comment]
closed with #77
