### ISSUE TITLE
DANK balance doesn't update when bridged/[FEATURE]

### ISSUE THREAD

**Issue by cosmohm** [district0x/memefactory#752]
# Problem

DANK balance doesn't show up in the right-hand corner automatically after bridging from ETH mainnet to Polygon.
Right now the user needs to disconnect and reconnect wallet to show the updated balance on memefactory website.

## Implementation

Add an explanation that you may need to disconnect and reconnect your wallet to see your bridged DANK. 
OR fix the issue if possible.

<img width="449" alt="Screen Shot 2022-03-15 at 4 37 45 PM" src="https://user-images.githubusercontent.com/80524059/158484019-02c6311e-c434-4694-bc1a-3b8b420b5d8e.png">

We also need text added to the bridge that tells the user that it may take up to ten minutes for their tokens to arrive on Polygon, so please be patient. You may need to reload the page for your balance to update.

**Comment by madvas** [comment]
As far as I tried, it is enough to just refresh the page. So, if that's the case for everybody, I'd make the last sentence as following: "Once the transaction succeed, switch your wallet to Polygon Mainnet where you'll receive your DANK within 15 minutes. If you have trouble receiving DANK, please try to refresh the page or contact us."

**Comment by Bradymck** [comment]
That works. I didn't have the issue with needed to reconnect either so this should be perfect.
