### ISSUE TITLE
Twitter bot on Discord/[BUG]

### ISSUE THREAD

**Issue by cosmohm** [district0x/memefactory#756]
### User Story

Twitter bot is currently only posting memes to #Meme-Factory channel on district0x Discord server when memes get challenged, but not when they get submitted or voted on. 

### Description

The Twitter bot should post all memes that get submitted, challenged or voted on memefactory.io to the d0x Discord server.

**Comment by madvas** [comment]
Yeah it should definitely post when a meme is submitted, but not when it gets voted on, because it is secret until user reveals it.

**Comment by madvas** [comment]
Additionally, we should not only post to the channel when memes are sumitted/challenged, but also parameter changes.
