### ISSUE TITLE
Twitter DANK faucet text invalid/[BUG]

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#764]
### Description

The new text format isn't registered as valid and gives an error when entering your URL to the tweet.  

<img width="468" alt="Screen Shot 2022-03-17 at 10 33 33 AM" src="https://user-images.githubusercontent.com/4667076/158861262-dc094879-209a-414b-9acb-5bfeee625b6c.png">

**Comment by madvas** [comment]
Can you paste link to the tweet that didn't work for you?

**Comment by Bradymck** [comment]
https://twitter.com/BradyMck_/status/1504499910086840321

**Comment by let4be** [comment]
Wanted to try out memefactory as well and I'm having a similar error(metamask wallet)
https://twitter.com/let4be/status/1505134234574508032

**Comment by ginesdt** [comment]
@let4be we deployed a fix for the faucet. Please give it another try.
