### ISSUE TITLE
feature/[FEATURE]Keep data on Submission Field

### ISSUE THREAD

**Issue by eastrgn** [district0x/memefactory#771]
# Problem

we need to keep uploading and writing on submit page. 

## Implementation

dont delete data from submission fields when loss in cancel or error transactions

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved. Is it linked to other issue?

**Comment by ginesdt** [comment]
This is done. closing issue.
