### ISSUE TITLE
Fix flickering when turning card for selling

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#83]
![meme-flickering2](https://user-images.githubusercontent.com/3857155/52615819-1b219280-2ec9-11e9-994f-450a412a1fbc.gif)

**Comment by jpmonettas** [comment]
wow, it doesn't look like that in my browser. But looks like something related to moving z-index of the overlay. First and last lines marked in https://github.com/district0x/memefactory/blob/master/src/memefactory/styles/component/compact_tile.clj#L40,L52

**Comment by fbielejec** [comment]
Can't reproduce: https://www.dropbox.com/s/1zrr19cq4i6ptfo/flicker.mp4?dl=0 @danielglauser can you?
