### ISSUE TITLE
Fix Transaction Log content jumping on opening

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#84]
There's always some weird jump of content when transaction log is opened. NameBazaar doesn't have that. 

![tx-log-jumping](https://user-images.githubusercontent.com/3857155/52616099-e95cfb80-2ec9-11e9-9955-8e78e6da2108.gif)

**Comment by jpmonettas** [comment]
I can't reproduce that on my Linux Chrome so no idea what can be causing it. Looks like something getting display none at the and of the animation.

**Comment by fbielejec** [comment]
Can't reproduce either: https://www.dropbox.com/s/dgviiklx7s5vhlq/jump.mp4?dl=0 @danielglauser  help :
)
