### ISSUE TITLE
No meme title when challenging meme

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#86]
Popup and transaction log show no title
![no_meme_title](https://user-images.githubusercontent.com/468572/52634728-4192fe00-2ec8-11e9-9872-072612ce0551.jpg)

**Comment by jpmonettas** [comment]
Hmm weird, I'm not seeing that issue 
![latest-screenshot](https://user-images.githubusercontent.com/786299/52637965-8eb6a600-2eaf-11e9-80e1-5fb1ab426889.png)

**Comment by fbielejec** [comment]
I had mu config pointing to ipfs node running on QA, which has some networking issues ATM. Can be closed
