### ISSUE TITLE
Add description field for MemeAuction

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#9]
In MemeAuction.sol for function `startAuction`, we'll add additional parameter `string _description`, which will be stored in `string public description`. This is intended for very short strings (20-40 characters), so I guess we can store it in blockchain state and not mess with IPFS. 
Validation of string length is not required, it's sufficient to do it on UI level. If somebody wants to pass long string, he'll pay for it.

**Comment by jpmonettas** [comment]
Added it https://github.com/district0x/memefactory/commit/acbda4ab68f04ec358f04ffec39812178abc32fb
