### ISSUE TITLE
Fix My Memefolio - Curated

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#92]
This has been reported many times. Juan is not able to reproduce it, but to me it doesn't work pretty much every single time. When I go to My Memefolio - Curated, list is just rarely complete. I curated more memes than the list displays. 

https://github.com/district0x/memefactory/issues/89#issuecomment-464002803

**Comment by madvas** [comment]
@fbielejec After your last PR there's been some progress, but still not quite right. With 1 address I got correct list in Curated, which I probably wouldn't get before: 
address: `0xafcf1a2bc71acf041c93012a2e552e31026dfeab `
![image](https://user-images.githubusercontent.com/3857155/53155608-ff686b80-35ef-11e9-98df-be3e8cb8564c.png)
![image](https://user-images.githubusercontent.com/3857155/53155648-1313d200-35f0-11e9-9cb0-e587c27f9f01.png)

But with other address I'm getting empty list again: 
address: `0xc238fa6ccc9d226e2c49644b36914611319fc3ff `
![image](https://user-images.githubusercontent.com/3857155/53155744-46eef780-35f0-11e9-9cc4-20dc9975e8fa.png)
![image](https://user-images.githubusercontent.com/3857155/53155798-684fe380-35f0-11e9-9e27-f0c239a73d01.png)

**Comment by fbielejec** [comment]
I could not reproduce, but I found: https://github.com/district0x/memefactory/issues/103

**Comment by madvas** [comment]
Hmm, I'm still being able to reproduce very easily by following scenario: 
1. With first account `0x4c3F13898913F15F12F902d6480178484063A6Fb` submit 3 memes
2. With second account `0xaFcF1a2bc71AcF041c93012A2E552e31026dFEAB` challenge all 3 memes and vote. Go to My Memefolio, correctly shows all 3 memes. 
3. With third account `0xC238fa6CcC9D226e2C49644b36914611319fc3Ff` vote for 3 memes. Nothing gets shown in My Memefolio - Curated

**Comment by fbielejec** [comment]
Aee you switching accounts while still on the memefolio page? Maybe its the same issue as I reported (#103)?

**Comment by madvas** [comment]
I refresh page after every account switch

**Comment by madvas** [comment]
I have more details on this bug: Meme correctly shows up in Memefolio - Curated only when user is either meme's creator who voted, or its challenger. When user is neither creator or challenger, just voter, a meme won't show up in his Memefolio - Curated.

**Comment by fbielejec** [comment]
I can reproduce that behaviour, many thanks.
