### ISSUE TITLE
Fix My Memefolio - Sold

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#93]
My Memefolio - Sold is sometimes troublesome. 

In this example, it doesn't display Registry Number next to hashtag. Warning in console is probably related. 
![image](https://user-images.githubusercontent.com/3857155/52929174-e05ea500-3375-11e9-8f28-86a7728266ac.png)
![image](https://user-images.githubusercontent.com/3857155/52929203-008e6400-3376-11e9-9c88-96d6b75aa7fd.png)

Sometimes problem with this page is more serious: https://github.com/district0x/memefactory/issues/89#issuecomment-464026457. Although, I cannot always reproduce this one, happens unpredictably.

**Comment by fbielejec** [comment]
addressed in #102
