### ISSUE TITLE
Memefolio switching URLs when clicking on tabs

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#99]
![image](https://user-images.githubusercontent.com/3857155/53155080-e3b09580-35ee-11e9-9737-8c2d268ae86f.png)
As you can see I'm on URL `http://localhost:4598/#/memefolio/?tab=curated`
When I click tab Curated again (or any other tab also) it takes me to URL `http://localhost:4598/#/memefolio/0xc238fa6ccc9d226e2c49644b36914611319fc3ff?tab=curated`. URL is supposed to stay without address. Also, title is other way around. When there's no address in URL it should show "My Memefolio". When there's address in URL it should show `Memefolio 0xc238fa...`
![image](https://user-images.githubusercontent.com/3857155/53155286-502b9480-35ef-11e9-9568-fa07a4be31c1.png)

**Comment by fbielejec** [comment]
addressed in #102
